<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellCardManagementAPIsLib\Models\AccountRestrictionRequest;

/**
 * Builder for model AccountRestrictionRequest
 *
 * @see AccountRestrictionRequest
 */
class AccountRestrictionRequestBuilder
{
    /**
     * @var AccountRestrictionRequest
     */
    private $instance;

    private function __construct(AccountRestrictionRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Account Restriction Request Builder object.
     */
    public static function init(): self
    {
        return new self(new AccountRestrictionRequest());
    }

    /**
     * Sets Col Co Id field.
     *
     * @param int|null $value
     */
    public function colCoId(?int $value): self
    {
        $this->instance->setColCoId($value);
        return $this;
    }

    /**
     * Unsets Col Co Id field.
     */
    public function unsetColCoId(): self
    {
        $this->instance->unsetColCoId();
        return $this;
    }

    /**
     * Sets Col Co Code field.
     *
     * @param int|null $value
     */
    public function colCoCode(?int $value): self
    {
        $this->instance->setColCoCode($value);
        return $this;
    }

    /**
     * Unsets Col Co Code field.
     */
    public function unsetColCoCode(): self
    {
        $this->instance->unsetColCoCode();
        return $this;
    }

    /**
     * Sets Payer Id field.
     *
     * @param int|null $value
     */
    public function payerId(?int $value): self
    {
        $this->instance->setPayerId($value);
        return $this;
    }

    /**
     * Unsets Payer Id field.
     */
    public function unsetPayerId(): self
    {
        $this->instance->unsetPayerId();
        return $this;
    }

    /**
     * Sets Payer Number field.
     *
     * @param string|null $value
     */
    public function payerNumber(?string $value): self
    {
        $this->instance->setPayerNumber($value);
        return $this;
    }

    /**
     * Unsets Payer Number field.
     */
    public function unsetPayerNumber(): self
    {
        $this->instance->unsetPayerNumber();
        return $this;
    }

    /**
     * Sets Account Id field.
     *
     * @param int|null $value
     */
    public function accountId(?int $value): self
    {
        $this->instance->setAccountId($value);
        return $this;
    }

    /**
     * Unsets Account Id field.
     */
    public function unsetAccountId(): self
    {
        $this->instance->unsetAccountId();
        return $this;
    }

    /**
     * Sets Account Number field.
     *
     * @param string|null $value
     */
    public function accountNumber(?string $value): self
    {
        $this->instance->setAccountNumber($value);
        return $this;
    }

    /**
     * Unsets Account Number field.
     */
    public function unsetAccountNumber(): self
    {
        $this->instance->unsetAccountNumber();
        return $this;
    }

    /**
     * Sets Reset Usage Restrictions field.
     *
     * @param bool|null $value
     */
    public function resetUsageRestrictions(?bool $value): self
    {
        $this->instance->setResetUsageRestrictions($value);
        return $this;
    }

    /**
     * Unsets Reset Usage Restrictions field.
     */
    public function unsetResetUsageRestrictions(): self
    {
        $this->instance->unsetResetUsageRestrictions();
        return $this;
    }

    /**
     * Sets Usage Restrictions field.
     *
     * @param array|null $value
     */
    public function usageRestrictions(?array $value): self
    {
        $this->instance->setUsageRestrictions($value);
        return $this;
    }

    /**
     * Initializes a new Account Restriction Request object.
     */
    public function build(): AccountRestrictionRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
