<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellCardManagementAPIsLib\Models\AccountRestrictionResponse;
use ShellCardManagementAPIsLib\Models\ErrorStatus;

/**
 * Builder for model AccountRestrictionResponse
 *
 * @see AccountRestrictionResponse
 */
class AccountRestrictionResponseBuilder
{
    /**
     * @var AccountRestrictionResponse
     */
    private $instance;

    private function __construct(AccountRestrictionResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new account restriction response Builder object.
     */
    public static function init(): self
    {
        return new self(new AccountRestrictionResponse());
    }

    /**
     * Sets request id field.
     */
    public function requestId(?string $value): self
    {
        $this->instance->setRequestId($value);
        return $this;
    }

    /**
     * Unsets request id field.
     */
    public function unsetRequestId(): self
    {
        $this->instance->unsetRequestId();
        return $this;
    }

    /**
     * Sets account id field.
     */
    public function accountId(?int $value): self
    {
        $this->instance->setAccountId($value);
        return $this;
    }

    /**
     * Sets account number field.
     */
    public function accountNumber(?string $value): self
    {
        $this->instance->setAccountNumber($value);
        return $this;
    }

    /**
     * Sets usage restriction status field.
     */
    public function usageRestrictionStatus(?string $value): self
    {
        $this->instance->setUsageRestrictionStatus($value);
        return $this;
    }

    /**
     * Sets usage restriction description field.
     */
    public function usageRestrictionDescription(?string $value): self
    {
        $this->instance->setUsageRestrictionDescription($value);
        return $this;
    }

    /**
     * Sets error field.
     */
    public function error(?ErrorStatus $value): self
    {
        $this->instance->setError($value);
        return $this;
    }

    /**
     * Initializes a new account restriction response object.
     */
    public function build(): AccountRestrictionResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
