<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellCardManagementAPIsLib\Models\AutoRenewCardResponse;
use ShellCardManagementAPIsLib\Models\AutoRenewCardResponseDataItems;

/**
 * Builder for model AutoRenewCardResponse
 *
 * @see AutoRenewCardResponse
 */
class AutoRenewCardResponseBuilder
{
    /**
     * @var AutoRenewCardResponse
     */
    private $instance;

    private function __construct(AutoRenewCardResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Auto Renew Card Response Builder object.
     */
    public static function init(): self
    {
        return new self(new AutoRenewCardResponse());
    }

    /**
     * Sets Main Reference field.
     *
     * @param int|null $value
     */
    public function mainReference(?int $value): self
    {
        $this->instance->setMainReference($value);
        return $this;
    }

    /**
     * Sets Request Id field.
     *
     * @param string|null $value
     */
    public function requestId(?string $value): self
    {
        $this->instance->setRequestId($value);
        return $this;
    }

    /**
     * Sets Status field.
     *
     * @param string|null $value
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Sets Data field.
     *
     * @param AutoRenewCardResponseDataItems[]|null $value
     */
    public function data(?array $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Initializes a new Auto Renew Card Response object.
     */
    public function build(): AutoRenewCardResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
