<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellCardManagementAPIsLib\Models\AutoRenewCardResponseDataItems;

/**
 * Builder for model AutoRenewCardResponseDataItems
 *
 * @see AutoRenewCardResponseDataItems
 */
class AutoRenewCardResponseDataItemsBuilder
{
    /**
     * @var AutoRenewCardResponseDataItems
     */
    private $instance;

    private function __construct(AutoRenewCardResponseDataItems $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new auto renew card response data items Builder object.
     */
    public static function init(): self
    {
        return new self(new AutoRenewCardResponseDataItems());
    }

    /**
     * Sets auto renew reference id field.
     */
    public function autoRenewReferenceId(?int $value): self
    {
        $this->instance->setAutoRenewReferenceId($value);
        return $this;
    }

    /**
     * Unsets auto renew reference id field.
     */
    public function unsetAutoRenewReferenceId(): self
    {
        $this->instance->unsetAutoRenewReferenceId();
        return $this;
    }

    /**
     * Sets card id and pan field.
     */
    public function cardIdAndPAN(?string $value): self
    {
        $this->instance->setCardIdAndPAN($value);
        return $this;
    }

    /**
     * Unsets card id and pan field.
     */
    public function unsetCardIdAndPAN(): self
    {
        $this->instance->unsetCardIdAndPAN();
        return $this;
    }

    /**
     * Initializes a new auto renew card response data items object.
     */
    public function build(): AutoRenewCardResponseDataItems
    {
        return CoreHelper::clone($this->instance);
    }
}
