<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellCardManagementAPIsLib\Models\BundleDetails;
use ShellCardManagementAPIsLib\Models\BundleDetailsResponse;

/**
 * Builder for model BundleDetails
 *
 * @see BundleDetails
 */
class BundleDetailsBuilder
{
    /**
     * @var BundleDetails
     */
    private $instance;

    private function __construct(BundleDetails $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Bundle Details Builder object.
     */
    public static function init(): self
    {
        return new self(new BundleDetails());
    }

    /**
     * Sets Request Id field.
     *
     * @param string|null $value
     */
    public function requestId(?string $value): self
    {
        $this->instance->setRequestId($value);
        return $this;
    }

    /**
     * Sets Status field.
     *
     * @param string|null $value
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Sets Data field.
     *
     * @param BundleDetailsResponse[]|null $value
     */
    public function data(?array $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Initializes a new Bundle Details object.
     */
    public function build(): BundleDetails
    {
        return CoreHelper::clone($this->instance);
    }
}
