<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellCardManagementAPIsLib\Models\BundleRestriction;
use ShellCardManagementAPIsLib\Models\DayTimeRestriction;
use ShellCardManagementAPIsLib\Models\LocationRestriction;
use ShellCardManagementAPIsLib\Models\ProductRestrictionCard;
use ShellCardManagementAPIsLib\Models\UsageRestrictionsCard;

/**
 * Builder for model BundleRestriction
 *
 * @see BundleRestriction
 */
class BundleRestrictionBuilder
{
    /**
     * @var BundleRestriction
     */
    private $instance;

    private function __construct(BundleRestriction $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new bundle restriction Builder object.
     */
    public static function init(): self
    {
        return new self(new BundleRestriction());
    }

    /**
     * Sets day time restriction action field.
     */
    public function dayTimeRestrictionAction(?string $value): self
    {
        $this->instance->setDayTimeRestrictionAction($value);
        return $this;
    }

    /**
     * Unsets day time restriction action field.
     */
    public function unsetDayTimeRestrictionAction(): self
    {
        $this->instance->unsetDayTimeRestrictionAction();
        return $this;
    }

    /**
     * Sets location restriction action field.
     */
    public function locationRestrictionAction(?string $value): self
    {
        $this->instance->setLocationRestrictionAction($value);
        return $this;
    }

    /**
     * Unsets location restriction action field.
     */
    public function unsetLocationRestrictionAction(): self
    {
        $this->instance->unsetLocationRestrictionAction();
        return $this;
    }

    /**
     * Sets usage restrictions field.
     */
    public function usageRestrictions(?UsageRestrictionsCard $value): self
    {
        $this->instance->setUsageRestrictions($value);
        return $this;
    }

    /**
     * Unsets usage restrictions field.
     */
    public function unsetUsageRestrictions(): self
    {
        $this->instance->unsetUsageRestrictions();
        return $this;
    }

    /**
     * Sets day time restrictions field.
     */
    public function dayTimeRestrictions(?DayTimeRestriction $value): self
    {
        $this->instance->setDayTimeRestrictions($value);
        return $this;
    }

    /**
     * Sets product restrictions field.
     */
    public function productRestrictions(?ProductRestrictionCard $value): self
    {
        $this->instance->setProductRestrictions($value);
        return $this;
    }

    /**
     * Unsets product restrictions field.
     */
    public function unsetProductRestrictions(): self
    {
        $this->instance->unsetProductRestrictions();
        return $this;
    }

    /**
     * Sets location restrictions field.
     */
    public function locationRestrictions(?LocationRestriction $value): self
    {
        $this->instance->setLocationRestrictions($value);
        return $this;
    }

    /**
     * Initializes a new bundle restriction object.
     */
    public function build(): BundleRestriction
    {
        return CoreHelper::clone($this->instance);
    }
}
