<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellCardManagementAPIsLib\Models\CardContact;
use ShellCardManagementAPIsLib\Models\CardDetail;
use ShellCardManagementAPIsLib\Models\PINContact;

/**
 * Builder for model CardDetail
 *
 * @see CardDetail
 */
class CardDetailBuilder
{
    /**
     * @var CardDetail
     */
    private $instance;

    private function __construct(CardDetail $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new card detail Builder object.
     */
    public static function init(): self
    {
        return new self(new CardDetail());
    }

    /**
     * Sets payer id field.
     */
    public function payerId(?int $value): self
    {
        $this->instance->setPayerId($value);
        return $this;
    }

    /**
     * Unsets payer id field.
     */
    public function unsetPayerId(): self
    {
        $this->instance->unsetPayerId();
        return $this;
    }

    /**
     * Sets payer number field.
     */
    public function payerNumber(?string $value): self
    {
        $this->instance->setPayerNumber($value);
        return $this;
    }

    /**
     * Unsets payer number field.
     */
    public function unsetPayerNumber(): self
    {
        $this->instance->unsetPayerNumber();
        return $this;
    }

    /**
     * Sets account id field.
     */
    public function accountId(?int $value): self
    {
        $this->instance->setAccountId($value);
        return $this;
    }

    /**
     * Unsets account id field.
     */
    public function unsetAccountId(): self
    {
        $this->instance->unsetAccountId();
        return $this;
    }

    /**
     * Sets account number field.
     */
    public function accountNumber(?string $value): self
    {
        $this->instance->setAccountNumber($value);
        return $this;
    }

    /**
     * Unsets account number field.
     */
    public function unsetAccountNumber(): self
    {
        $this->instance->unsetAccountNumber();
        return $this;
    }

    /**
     * Sets col co code field.
     */
    public function colCoCode(?int $value): self
    {
        $this->instance->setColCoCode($value);
        return $this;
    }

    /**
     * Unsets col co code field.
     */
    public function unsetColCoCode(): self
    {
        $this->instance->unsetColCoCode();
        return $this;
    }

    /**
     * Sets col co id field.
     */
    public function colCoId(?int $value): self
    {
        $this->instance->setColCoId($value);
        return $this;
    }

    /**
     * Unsets col co id field.
     */
    public function unsetColCoId(): self
    {
        $this->instance->unsetColCoId();
        return $this;
    }

    /**
     * Sets card type id field.
     */
    public function cardTypeId(?int $value): self
    {
        $this->instance->setCardTypeId($value);
        return $this;
    }

    /**
     * Unsets card type id field.
     */
    public function unsetCardTypeId(): self
    {
        $this->instance->unsetCardTypeId();
        return $this;
    }

    /**
     * Sets token type id field.
     */
    public function tokenTypeId(?int $value): self
    {
        $this->instance->setTokenTypeId($value);
        return $this;
    }

    /**
     * Unsets token type id field.
     */
    public function unsetTokenTypeId(): self
    {
        $this->instance->unsetTokenTypeId();
        return $this;
    }

    /**
     * Sets emboss text field.
     */
    public function embossText(?string $value): self
    {
        $this->instance->setEmbossText($value);
        return $this;
    }

    /**
     * Unsets emboss text field.
     */
    public function unsetEmbossText(): self
    {
        $this->instance->unsetEmbossText();
        return $this;
    }

    /**
     * Sets vrn field.
     */
    public function vRN(?string $value): self
    {
        $this->instance->setVRN($value);
        return $this;
    }

    /**
     * Unsets vrn field.
     */
    public function unsetVRN(): self
    {
        $this->instance->unsetVRN();
        return $this;
    }

    /**
     * Sets driver name field.
     */
    public function driverName(?string $value): self
    {
        $this->instance->setDriverName($value);
        return $this;
    }

    /**
     * Unsets driver name field.
     */
    public function unsetDriverName(): self
    {
        $this->instance->unsetDriverName();
        return $this;
    }

    /**
     * Sets odometer input required field.
     */
    public function odometerInputRequired(?bool $value): self
    {
        $this->instance->setOdometerInputRequired($value);
        return $this;
    }

    /**
     * Sets fleet id input required field.
     */
    public function fleetIdInputRequired(?bool $value): self
    {
        $this->instance->setFleetIdInputRequired($value);
        return $this;
    }

    /**
     * Sets purchase category id field.
     */
    public function purchaseCategoryId(?int $value): self
    {
        $this->instance->setPurchaseCategoryId($value);
        return $this;
    }

    /**
     * Unsets purchase category id field.
     */
    public function unsetPurchaseCategoryId(): self
    {
        $this->instance->unsetPurchaseCategoryId();
        return $this;
    }

    /**
     * Sets self selected encrypted pin field.
     */
    public function selfSelectedEncryptedPIN(?string $value): self
    {
        $this->instance->setSelfSelectedEncryptedPIN($value);
        return $this;
    }

    /**
     * Sets self selected pinkey id field.
     */
    public function selfSelectedPINKeyID(?string $value): self
    {
        $this->instance->setSelfSelectedPINKeyID($value);
        return $this;
    }

    /**
     * Unsets self selected pinkey id field.
     */
    public function unsetSelfSelectedPINKeyID(): self
    {
        $this->instance->unsetSelfSelectedPINKeyID();
        return $this;
    }

    /**
     * Sets self selected pinsession key field.
     */
    public function selfSelectedPINSessionKey(?string $value): self
    {
        $this->instance->setSelfSelectedPINSessionKey($value);
        return $this;
    }

    /**
     * Unsets self selected pinsession key field.
     */
    public function unsetSelfSelectedPINSessionKey(): self
    {
        $this->instance->unsetSelfSelectedPINSessionKey();
        return $this;
    }

    /**
     * Sets card group id field.
     */
    public function cardGroupId(?int $value): self
    {
        $this->instance->setCardGroupId($value);
        return $this;
    }

    /**
     * Unsets card group id field.
     */
    public function unsetCardGroupId(): self
    {
        $this->instance->unsetCardGroupId();
        return $this;
    }

    /**
     * Sets card group name field.
     */
    public function cardGroupName(?string $value): self
    {
        $this->instance->setCardGroupName($value);
        return $this;
    }

    /**
     * Unsets card group name field.
     */
    public function unsetCardGroupName(): self
    {
        $this->instance->unsetCardGroupName();
        return $this;
    }

    /**
     * Sets is new card group field.
     */
    public function isNewCardGroup(?bool $value): self
    {
        $this->instance->setIsNewCardGroup($value);
        return $this;
    }

    /**
     * Sets emboss card group field.
     */
    public function embossCardGroup(?bool $value): self
    {
        $this->instance->setEmbossCardGroup($value);
        return $this;
    }

    /**
     * Sets card delivery type field.
     */
    public function cardDeliveryType(?int $value): self
    {
        $this->instance->setCardDeliveryType($value);
        return $this;
    }

    /**
     * Sets card contact field.
     */
    public function cardContact(?CardContact $value): self
    {
        $this->instance->setCardContact($value);
        return $this;
    }

    /**
     * Sets pindelivery address type field.
     */
    public function pINDeliveryAddressType(?int $value): self
    {
        $this->instance->setPINDeliveryAddressType($value);
        return $this;
    }

    /**
     * Unsets pindelivery address type field.
     */
    public function unsetPINDeliveryAddressType(): self
    {
        $this->instance->unsetPINDeliveryAddressType();
        return $this;
    }

    /**
     * Sets pinadvice type field.
     */
    public function pINAdviceType(?int $value): self
    {
        $this->instance->setPINAdviceType($value);
        return $this;
    }

    /**
     * Sets pincontact field.
     */
    public function pINContact(?PINContact $value): self
    {
        $this->instance->setPINContact($value);
        return $this;
    }

    /**
     * Sets notify caller field.
     */
    public function notifyCaller(?bool $value): self
    {
        $this->instance->setNotifyCaller($value);
        return $this;
    }

    /**
     * Sets caller field.
     */
    public function caller(?string $value): self
    {
        $this->instance->setCaller($value);
        return $this;
    }

    /**
     * Unsets caller field.
     */
    public function unsetCaller(): self
    {
        $this->instance->unsetCaller();
        return $this;
    }

    /**
     * Sets notify caller on sync field.
     */
    public function notifyCallerOnSync(?bool $value): self
    {
        $this->instance->setNotifyCallerOnSync($value);
        return $this;
    }

    /**
     * Sets validate fleet id field.
     */
    public function validateFleetId(?bool $value): self
    {
        $this->instance->setValidateFleetId($value);
        return $this;
    }

    /**
     * Sets fleet option field.
     */
    public function fleetOption(?string $value): self
    {
        $this->instance->setFleetOption($value);
        return $this;
    }

    /**
     * Unsets fleet option field.
     */
    public function unsetFleetOption(): self
    {
        $this->instance->unsetFleetOption();
        return $this;
    }

    /**
     * Sets bundle id field.
     */
    public function bundleId(?string $value): self
    {
        $this->instance->setBundleId($value);
        return $this;
    }

    /**
     * Unsets bundle id field.
     */
    public function unsetBundleId(): self
    {
        $this->instance->unsetBundleId();
        return $this;
    }

    /**
     * Sets usage restriction action field.
     */
    public function usageRestrictionAction(?string $value): self
    {
        $this->instance->setUsageRestrictionAction($value);
        return $this;
    }

    /**
     * Unsets usage restriction action field.
     */
    public function unsetUsageRestrictionAction(): self
    {
        $this->instance->unsetUsageRestrictionAction();
        return $this;
    }

    /**
     * Sets product restriction action field.
     */
    public function productRestrictionAction(?string $value): self
    {
        $this->instance->setProductRestrictionAction($value);
        return $this;
    }

    /**
     * Unsets product restriction action field.
     */
    public function unsetProductRestrictionAction(): self
    {
        $this->instance->unsetProductRestrictionAction();
        return $this;
    }

    /**
     * Sets products field.
     */
    public function products(?array $value): self
    {
        $this->instance->setProducts($value);
        return $this;
    }

    /**
     * Sets product groups field.
     */
    public function productGroups(?array $value): self
    {
        $this->instance->setProductGroups($value);
        return $this;
    }

    /**
     * Sets expiry date field.
     */
    public function expiryDate(?string $value): self
    {
        $this->instance->setExpiryDate($value);
        return $this;
    }

    /**
     * Unsets expiry date field.
     */
    public function unsetExpiryDate(): self
    {
        $this->instance->unsetExpiryDate();
        return $this;
    }

    /**
     * Sets client reference id field.
     */
    public function clientReferenceId(?string $value): self
    {
        $this->instance->setClientReferenceId($value);
        return $this;
    }

    /**
     * Unsets client reference id field.
     */
    public function unsetClientReferenceId(): self
    {
        $this->instance->unsetClientReferenceId();
        return $this;
    }

    /**
     * Sets auto renew field.
     */
    public function autoRenew(?int $value): self
    {
        $this->instance->setAutoRenew($value);
        return $this;
    }

    /**
     * Initializes a new card detail object.
     */
    public function build(): CardDetail
    {
        return CoreHelper::clone($this->instance);
    }
}
