<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellCardManagementAPIsLib\Models\CardManagementV1UpdatestatusRequest;

/**
 * Builder for model CardManagementV1UpdatestatusRequest
 *
 * @see CardManagementV1UpdatestatusRequest
 */
class CardManagementV1UpdatestatusRequestBuilder
{
    /**
     * @var CardManagementV1UpdatestatusRequest
     */
    private $instance;

    private function __construct(CardManagementV1UpdatestatusRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new card management v1 updatestatus request Builder object.
     */
    public static function init(array $cards, string $targetStatus): self
    {
        return new self(new CardManagementV1UpdatestatusRequest($cards, $targetStatus));
    }

    /**
     * Sets reason id field.
     */
    public function reasonId(?int $value): self
    {
        $this->instance->setReasonId($value);
        return $this;
    }

    /**
     * Unsets reason id field.
     */
    public function unsetReasonId(): self
    {
        $this->instance->unsetReasonId();
        return $this;
    }

    /**
     * Sets reason text field.
     */
    public function reasonText(?string $value): self
    {
        $this->instance->setReasonText($value);
        return $this;
    }

    /**
     * Unsets reason text field.
     */
    public function unsetReasonText(): self
    {
        $this->instance->unsetReasonText();
        return $this;
    }

    /**
     * Initializes a new card management v1 updatestatus request object.
     */
    public function build(): CardManagementV1UpdatestatusRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
