<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellCardManagementAPIsLib\Models\CardDeliveryAddress;

/**
 * Builder for model CardDeliveryAddress
 *
 * @see CardDeliveryAddress
 */
class CardDeliveryAddressBuilder
{
    /**
     * @var CardDeliveryAddress
     */
    private $instance;

    private function __construct(CardDeliveryAddress $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Card Delivery Address Builder object.
     *
     * @param string $companyName
     * @param int $addressId
     * @param string $addressLine1
     * @param string $zipCode
     * @param int $countryId
     * @param string $countryISOCode
     * @param string $country
     */
    public static function init(
        string $companyName,
        int $addressId,
        string $addressLine1,
        string $zipCode,
        int $countryId,
        string $countryISOCode,
        string $country
    ): self {
        return new self(new CardDeliveryAddress(
            $companyName,
            $addressId,
            $addressLine1,
            $zipCode,
            $countryId,
            $countryISOCode,
            $country
        ));
    }

    /**
     * Sets Contact Fore Name field.
     *
     * @param string|null $value
     */
    public function contactForeName(?string $value): self
    {
        $this->instance->setContactForeName($value);
        return $this;
    }

    /**
     * Sets Contact Middle Name field.
     *
     * @param string|null $value
     */
    public function contactMiddleName(?string $value): self
    {
        $this->instance->setContactMiddleName($value);
        return $this;
    }

    /**
     * Sets Contact Last Name field.
     *
     * @param string|null $value
     */
    public function contactLastName(?string $value): self
    {
        $this->instance->setContactLastName($value);
        return $this;
    }

    /**
     * Sets Contact Title field.
     *
     * @param string|null $value
     */
    public function contactTitle(?string $value): self
    {
        $this->instance->setContactTitle($value);
        return $this;
    }

    /**
     * Sets Address Line 2 field.
     *
     * @param string|null $value
     */
    public function addressLine2(?string $value): self
    {
        $this->instance->setAddressLine2($value);
        return $this;
    }

    /**
     * Sets Address Line 3 field.
     *
     * @param string|null $value
     */
    public function addressLine3(?string $value): self
    {
        $this->instance->setAddressLine3($value);
        return $this;
    }

    /**
     * Sets City field.
     *
     * @param string|null $value
     */
    public function city(?string $value): self
    {
        $this->instance->setCity($value);
        return $this;
    }

    /**
     * Sets Region Id field.
     *
     * @param int|null $value
     */
    public function regionId(?int $value): self
    {
        $this->instance->setRegionId($value);
        return $this;
    }

    /**
     * Unsets Region Id field.
     */
    public function unsetRegionId(): self
    {
        $this->instance->unsetRegionId();
        return $this;
    }

    /**
     * Sets Region field.
     *
     * @param string|null $value
     */
    public function region(?string $value): self
    {
        $this->instance->setRegion($value);
        return $this;
    }

    /**
     * Initializes a new Card Delivery Address object.
     */
    public function build(): CardDeliveryAddress
    {
        return CoreHelper::clone($this->instance);
    }
}
