<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellCardManagementAPIsLib\Models\CardSummaryResponse;
use ShellCardManagementAPIsLib\Models\SummaryResponse;

/**
 * Builder for model CardSummaryResponse
 *
 * @see CardSummaryResponse
 */
class CardSummaryResponseBuilder
{
    /**
     * @var CardSummaryResponse
     */
    private $instance;

    private function __construct(CardSummaryResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Card Summary Response Builder object.
     */
    public static function init(): self
    {
        return new self(new CardSummaryResponse());
    }

    /**
     * Sets Request Id field.
     *
     * @param string|null $value
     */
    public function requestId(?string $value): self
    {
        $this->instance->setRequestId($value);
        return $this;
    }

    /**
     * Sets Status field.
     *
     * @param string|null $value
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Sets Data field.
     *
     * @param SummaryResponse[]|null $value
     */
    public function data(?array $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Initializes a new Card Summary Response object.
     */
    public function build(): CardSummaryResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
