<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellCardManagementAPIsLib\Models\CardDetail;
use ShellCardManagementAPIsLib\Models\CardManagementV1OrdercardRequest;

/**
 * Builder for model CardManagementV1OrdercardRequest
 *
 * @see CardManagementV1OrdercardRequest
 */
class CardManagementV1OrdercardRequestBuilder
{
    /**
     * @var CardManagementV1OrdercardRequest
     */
    private $instance;

    private function __construct(CardManagementV1OrdercardRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Card Management V1 Ordercard Request Builder object.
     */
    public static function init(): self
    {
        return new self(new CardManagementV1OrdercardRequest());
    }

    /**
     * Sets Card Details field.
     *
     * @param CardDetail[]|null $value
     */
    public function cardDetails(?array $value): self
    {
        $this->instance->setCardDetails($value);
        return $this;
    }

    /**
     * Initializes a new Card Management V1 Ordercard Request object.
     */
    public function build(): CardManagementV1OrdercardRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
