<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellCardManagementAPIsLib\Models\CardRestrictionRes;
use ShellCardManagementAPIsLib\Models\ErrorObject;
use ShellCardManagementAPIsLib\Models\RestrictioncardsRes;

/**
 * Builder for model CardRestrictionRes
 *
 * @see CardRestrictionRes
 */
class CardRestrictionResBuilder
{
    /**
     * @var CardRestrictionRes
     */
    private $instance;

    private function __construct(CardRestrictionRes $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Card Restriction Res Builder object.
     */
    public static function init(): self
    {
        return new self(new CardRestrictionRes());
    }

    /**
     * Sets Request Id field.
     *
     * @param string|null $value
     */
    public function requestId(?string $value): self
    {
        $this->instance->setRequestId($value);
        return $this;
    }

    /**
     * Sets Status field.
     *
     * @param string|null $value
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Sets Data field.
     *
     * @param RestrictioncardsRes[]|null $value
     */
    public function data(?array $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Sets Errors field.
     *
     * @param ErrorObject|null $value
     */
    public function errors(?ErrorObject $value): self
    {
        $this->instance->setErrors($value);
        return $this;
    }

    /**
     * Initializes a new Card Restriction Res object.
     */
    public function build(): CardRestrictionRes
    {
        return CoreHelper::clone($this->instance);
    }
}
