<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellCardManagementAPIsLib\Models\CreateCardGroupRes;
use ShellCardManagementAPIsLib\Models\CreateCardGroupResponse;

/**
 * Builder for model CreateCardGroupRes
 *
 * @see CreateCardGroupRes
 */
class CreateCardGroupResBuilder
{
    /**
     * @var CreateCardGroupRes
     */
    private $instance;

    private function __construct(CreateCardGroupRes $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Create Card Group Res Builder object.
     */
    public static function init(): self
    {
        return new self(new CreateCardGroupRes());
    }

    /**
     * Sets Request Id field.
     *
     * @param string|null $value
     */
    public function requestId(?string $value): self
    {
        $this->instance->setRequestId($value);
        return $this;
    }

    /**
     * Sets Status field.
     *
     * @param string|null $value
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Sets Data field.
     *
     * @param CreateCardGroupResponse[]|null $value
     */
    public function data(?array $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Initializes a new Create Card Group Res object.
     */
    public function build(): CreateCardGroupRes
    {
        return CoreHelper::clone($this->instance);
    }
}
