<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellCardManagementAPIsLib\Models\CreateCardResponse;

/**
 * Builder for model CreateCardResponse
 *
 * @see CreateCardResponse
 */
class CreateCardResponseBuilder
{
    /**
     * @var CreateCardResponse
     */
    private $instance;

    private function __construct(CreateCardResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new create card response Builder object.
     */
    public static function init(): self
    {
        return new self(new CreateCardResponse());
    }

    /**
     * Sets driver and vrn field.
     */
    public function driverAndVRN(?string $value): self
    {
        $this->instance->setDriverAndVRN($value);
        return $this;
    }

    /**
     * Unsets driver and vrn field.
     */
    public function unsetDriverAndVRN(): self
    {
        $this->instance->unsetDriverAndVRN();
        return $this;
    }

    /**
     * Sets order card reference field.
     */
    public function orderCardReference(?int $value): self
    {
        $this->instance->setOrderCardReference($value);
        return $this;
    }

    /**
     * Unsets order card reference field.
     */
    public function unsetOrderCardReference(): self
    {
        $this->instance->unsetOrderCardReference();
        return $this;
    }

    /**
     * Initializes a new create card response object.
     */
    public function build(): CreateCardResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
