<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellCardManagementAPIsLib\Models\DeleteBundleRequest;

/**
 * Builder for model DeleteBundleRequest
 *
 * @see DeleteBundleRequest
 */
class DeleteBundleRequestBuilder
{
    /**
     * @var DeleteBundleRequest
     */
    private $instance;

    private function __construct(DeleteBundleRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Delete Bundle Request Builder object.
     *
     * @param string $bundleId
     */
    public static function init(string $bundleId): self
    {
        return new self(new DeleteBundleRequest($bundleId));
    }

    /**
     * Sets Col Co Code field.
     *
     * @param int|null $value
     */
    public function colCoCode(?int $value): self
    {
        $this->instance->setColCoCode($value);
        return $this;
    }

    /**
     * Sets Col Co Id field.
     *
     * @param int|null $value
     */
    public function colCoId(?int $value): self
    {
        $this->instance->setColCoId($value);
        return $this;
    }

    /**
     * Sets Payer Number field.
     *
     * @param string|null $value
     */
    public function payerNumber(?string $value): self
    {
        $this->instance->setPayerNumber($value);
        return $this;
    }

    /**
     * Sets Payer Id field.
     *
     * @param int|null $value
     */
    public function payerId(?int $value): self
    {
        $this->instance->setPayerId($value);
        return $this;
    }

    /**
     * Sets Account Id field.
     *
     * @param int|null $value
     */
    public function accountId(?int $value): self
    {
        $this->instance->setAccountId($value);
        return $this;
    }

    /**
     * Sets Account Number field.
     *
     * @param string|null $value
     */
    public function accountNumber(?string $value): self
    {
        $this->instance->setAccountNumber($value);
        return $this;
    }

    /**
     * Initializes a new Delete Bundle Request object.
     */
    public function build(): DeleteBundleRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
