<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellCardManagementAPIsLib\Models\DeleteBundleResponse;
use ShellCardManagementAPIsLib\Models\ErrorStatus;

/**
 * Builder for model DeleteBundleResponse
 *
 * @see DeleteBundleResponse
 */
class DeleteBundleResponseBuilder
{
    /**
     * @var DeleteBundleResponse
     */
    private $instance;

    private function __construct(DeleteBundleResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Delete Bundle Response Builder object.
     */
    public static function init(): self
    {
        return new self(new DeleteBundleResponse());
    }

    /**
     * Sets Request Id field.
     *
     * @param string|null $value
     */
    public function requestId(?string $value): self
    {
        $this->instance->setRequestId($value);
        return $this;
    }

    /**
     * Sets Error field.
     *
     * @param ErrorStatus|null $value
     */
    public function error(?ErrorStatus $value): self
    {
        $this->instance->setError($value);
        return $this;
    }

    /**
     * Initializes a new Delete Bundle Response object.
     */
    public function build(): DeleteBundleResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
