<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellCardManagementAPIsLib\Models\DeliveryAddressUpdateReferences;

/**
 * Builder for model DeliveryAddressUpdateReferences
 *
 * @see DeliveryAddressUpdateReferences
 */
class DeliveryAddressUpdateReferencesBuilder
{
    /**
     * @var DeliveryAddressUpdateReferences
     */
    private $instance;

    private function __construct(DeliveryAddressUpdateReferences $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Delivery Address Update References Builder object.
     */
    public static function init(): self
    {
        return new self(new DeliveryAddressUpdateReferences());
    }

    /**
     * Sets Card Id field.
     *
     * @param int|null $value
     */
    public function cardId(?int $value): self
    {
        $this->instance->setCardId($value);
        return $this;
    }

    /**
     * Sets Card PAN field.
     *
     * @param string|null $value
     */
    public function cardPAN(?string $value): self
    {
        $this->instance->setCardPAN($value);
        return $this;
    }

    /**
     * Sets Account Id field.
     *
     * @param int|null $value
     */
    public function accountId(?int $value): self
    {
        $this->instance->setAccountId($value);
        return $this;
    }

    /**
     * Sets Account Number field.
     *
     * @param string|null $value
     */
    public function accountNumber(?string $value): self
    {
        $this->instance->setAccountNumber($value);
        return $this;
    }

    /**
     * Sets Reference Id field.
     *
     * @param int|null $value
     */
    public function referenceId(?int $value): self
    {
        $this->instance->setReferenceId($value);
        return $this;
    }

    /**
     * Sets Error Info field.
     *
     * @param string|null $value
     */
    public function errorInfo(?string $value): self
    {
        $this->instance->setErrorInfo($value);
        return $this;
    }

    /**
     * Initializes a new Delivery Address Update References object.
     */
    public function build(): DeliveryAddressUpdateReferences
    {
        return CoreHelper::clone($this->instance);
    }
}
