<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellCardManagementAPIsLib\Models\CountryRestriction;
use ShellCardManagementAPIsLib\Models\LocationRestriction;
use ShellCardManagementAPIsLib\Models\NetworkRestriction;
use ShellCardManagementAPIsLib\Models\PartnerSiteRestriction;
use ShellCardManagementAPIsLib\Models\ShellSiteRestriction;

/**
 * Builder for model LocationRestriction
 *
 * @see LocationRestriction
 */
class LocationRestrictionBuilder
{
    /**
     * @var LocationRestriction
     */
    private $instance;

    private function __construct(LocationRestriction $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Location Restriction Builder object.
     */
    public static function init(): self
    {
        return new self(new LocationRestriction());
    }

    /**
     * Sets Country Restrictions field.
     *
     * @param CountryRestriction|null $value
     */
    public function countryRestrictions(?CountryRestriction $value): self
    {
        $this->instance->setCountryRestrictions($value);
        return $this;
    }

    /**
     * Sets Network Restrictions field.
     *
     * @param NetworkRestriction[]|null $value
     */
    public function networkRestrictions(?array $value): self
    {
        $this->instance->setNetworkRestrictions($value);
        return $this;
    }

    /**
     * Sets Shell Site Restrictions field.
     *
     * @param ShellSiteRestriction[]|null $value
     */
    public function shellSiteRestrictions(?array $value): self
    {
        $this->instance->setShellSiteRestrictions($value);
        return $this;
    }

    /**
     * Sets Partner Site Restrictions field.
     *
     * @param PartnerSiteRestriction[]|null $value
     */
    public function partnerSiteRestrictions(?array $value): self
    {
        $this->instance->setPartnerSiteRestrictions($value);
        return $this;
    }

    /**
     * Initializes a new Location Restriction object.
     */
    public function build(): LocationRestriction
    {
        return CoreHelper::clone($this->instance);
    }
}
