<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellCardManagementAPIsLib\Models\LocationRestrictionsCountryRestrictions;

/**
 * Builder for model LocationRestrictionsCountryRestrictions
 *
 * @see LocationRestrictionsCountryRestrictions
 */
class LocationRestrictionsCountryRestrictionsBuilder
{
    /**
     * @var LocationRestrictionsCountryRestrictions
     */
    private $instance;

    private function __construct(LocationRestrictionsCountryRestrictions $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new location restrictions country restrictions Builder object.
     */
    public static function init(bool $exclusive, array $countries): self
    {
        return new self(new LocationRestrictionsCountryRestrictions($exclusive, $countries));
    }

    /**
     * Initializes a new location restrictions country restrictions object.
     */
    public function build(): LocationRestrictionsCountryRestrictions
    {
        return CoreHelper::clone($this->instance);
    }
}
