<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellCardManagementAPIsLib\Models\OrderCardEnquiryResponse;

/**
 * Builder for model OrderCardEnquiryResponse
 *
 * @see OrderCardEnquiryResponse
 */
class OrderCardEnquiryResponseBuilder
{
    /**
     * @var OrderCardEnquiryResponse
     */
    private $instance;

    private function __construct(OrderCardEnquiryResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new order card enquiry response Builder object.
     */
    public static function init(): self
    {
        return new self(new OrderCardEnquiryResponse());
    }

    /**
     * Sets request id field.
     */
    public function requestId(?string $value): self
    {
        $this->instance->setRequestId($value);
        return $this;
    }

    /**
     * Sets status field.
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Sets data field.
     */
    public function data(?array $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Initializes a new order card enquiry response object.
     */
    public function build(): OrderCardEnquiryResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
