<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellCardManagementAPIsLib\Models\OrderCardRequest;

/**
 * Builder for model OrderCardRequest
 *
 * @see OrderCardRequest
 */
class OrderCardRequestBuilder
{
    /**
     * @var OrderCardRequest
     */
    private $instance;

    private function __construct(OrderCardRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new order card request Builder object.
     */
    public static function init(): self
    {
        return new self(new OrderCardRequest());
    }

    /**
     * Sets card details field.
     */
    public function cardDetails(?array $value): self
    {
        $this->instance->setCardDetails($value);
        return $this;
    }

    /**
     * Initializes a new order card request object.
     */
    public function build(): OrderCardRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
