<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellCardManagementAPIsLib\Models\OrderCardEnquiry;

/**
 * Builder for model OrderCardEnquiry
 *
 * @see OrderCardEnquiry
 */
class OrderCardEnquiryBuilder
{
    /**
     * @var OrderCardEnquiry
     */
    private $instance;

    private function __construct(OrderCardEnquiry $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Order Card Enquiry Builder object.
     */
    public static function init(): self
    {
        return new self(new OrderCardEnquiry());
    }

    /**
     * Sets Account Id field.
     *
     * @param int|null $value
     */
    public function accountId(?int $value): self
    {
        $this->instance->setAccountId($value);
        return $this;
    }

    /**
     * Unsets Account Id field.
     */
    public function unsetAccountId(): self
    {
        $this->instance->unsetAccountId();
        return $this;
    }

    /**
     * Sets Account Number field.
     *
     * @param string|null $value
     */
    public function accountNumber(?string $value): self
    {
        $this->instance->setAccountNumber($value);
        return $this;
    }

    /**
     * Unsets Account Number field.
     */
    public function unsetAccountNumber(): self
    {
        $this->instance->unsetAccountNumber();
        return $this;
    }

    /**
     * Sets BCO Reference field.
     *
     * @param int|null $value
     */
    public function bCOReference(?int $value): self
    {
        $this->instance->setBCOReference($value);
        return $this;
    }

    /**
     * Unsets BCO Reference field.
     */
    public function unsetBCOReference(): self
    {
        $this->instance->unsetBCOReference();
        return $this;
    }

    /**
     * Sets BCO Row Number field.
     *
     * @param int|null $value
     */
    public function bCORowNumber(?int $value): self
    {
        $this->instance->setBCORowNumber($value);
        return $this;
    }

    /**
     * Unsets BCO Row Number field.
     */
    public function unsetBCORowNumber(): self
    {
        $this->instance->unsetBCORowNumber();
        return $this;
    }

    /**
     * Sets Card Group Id field.
     *
     * @param int|null $value
     */
    public function cardGroupId(?int $value): self
    {
        $this->instance->setCardGroupId($value);
        return $this;
    }

    /**
     * Unsets Card Group Id field.
     */
    public function unsetCardGroupId(): self
    {
        $this->instance->unsetCardGroupId();
        return $this;
    }

    /**
     * Sets Card Group Name field.
     *
     * @param string|null $value
     */
    public function cardGroupName(?string $value): self
    {
        $this->instance->setCardGroupName($value);
        return $this;
    }

    /**
     * Unsets Card Group Name field.
     */
    public function unsetCardGroupName(): self
    {
        $this->instance->unsetCardGroupName();
        return $this;
    }

    /**
     * Sets Card Id field.
     *
     * @param int|null $value
     */
    public function cardId(?int $value): self
    {
        $this->instance->setCardId($value);
        return $this;
    }

    /**
     * Unsets Card Id field.
     */
    public function unsetCardId(): self
    {
        $this->instance->unsetCardId();
        return $this;
    }

    /**
     * Sets Card PAN field.
     *
     * @param string|null $value
     */
    public function cardPAN(?string $value): self
    {
        $this->instance->setCardPAN($value);
        return $this;
    }

    /**
     * Unsets Card PAN field.
     */
    public function unsetCardPAN(): self
    {
        $this->instance->unsetCardPAN();
        return $this;
    }

    /**
     * Sets Masked PAN field.
     *
     * @param string|null $value
     */
    public function maskedPAN(?string $value): self
    {
        $this->instance->setMaskedPAN($value);
        return $this;
    }

    /**
     * Unsets Masked PAN field.
     */
    public function unsetMaskedPAN(): self
    {
        $this->instance->unsetMaskedPAN();
        return $this;
    }

    /**
     * Sets PANID field.
     *
     * @param float|null $value
     */
    public function pANID(?float $value): self
    {
        $this->instance->setPANID($value);
        return $this;
    }

    /**
     * Unsets PANID field.
     */
    public function unsetPANID(): self
    {
        $this->instance->unsetPANID();
        return $this;
    }

    /**
     * Sets Card Type Code field.
     *
     * @param string|null $value
     */
    public function cardTypeCode(?string $value): self
    {
        $this->instance->setCardTypeCode($value);
        return $this;
    }

    /**
     * Unsets Card Type Code field.
     */
    public function unsetCardTypeCode(): self
    {
        $this->instance->unsetCardTypeCode();
        return $this;
    }

    /**
     * Sets Card Type Id field.
     *
     * @param int|null $value
     */
    public function cardTypeId(?int $value): self
    {
        $this->instance->setCardTypeId($value);
        return $this;
    }

    /**
     * Unsets Card Type Id field.
     */
    public function unsetCardTypeId(): self
    {
        $this->instance->unsetCardTypeId();
        return $this;
    }

    /**
     * Sets Card Type Name field.
     *
     * @param string|null $value
     */
    public function cardTypeName(?string $value): self
    {
        $this->instance->setCardTypeName($value);
        return $this;
    }

    /**
     * Unsets Card Type Name field.
     */
    public function unsetCardTypeName(): self
    {
        $this->instance->unsetCardTypeName();
        return $this;
    }

    /**
     * Sets Driver Name field.
     *
     * @param string|null $value
     */
    public function driverName(?string $value): self
    {
        $this->instance->setDriverName($value);
        return $this;
    }

    /**
     * Unsets Driver Name field.
     */
    public function unsetDriverName(): self
    {
        $this->instance->unsetDriverName();
        return $this;
    }

    /**
     * Sets Error Code field.
     *
     * @param string|null $value
     */
    public function errorCode(?string $value): self
    {
        $this->instance->setErrorCode($value);
        return $this;
    }

    /**
     * Unsets Error Code field.
     */
    public function unsetErrorCode(): self
    {
        $this->instance->unsetErrorCode();
        return $this;
    }

    /**
     * Sets Error Description field.
     *
     * @param string|null $value
     */
    public function errorDescription(?string $value): self
    {
        $this->instance->setErrorDescription($value);
        return $this;
    }

    /**
     * Unsets Error Description field.
     */
    public function unsetErrorDescription(): self
    {
        $this->instance->unsetErrorDescription();
        return $this;
    }

    /**
     * Sets Gateway Sync Error Code field.
     *
     * @param string|null $value
     */
    public function gatewaySyncErrorCode(?string $value): self
    {
        $this->instance->setGatewaySyncErrorCode($value);
        return $this;
    }

    /**
     * Unsets Gateway Sync Error Code field.
     */
    public function unsetGatewaySyncErrorCode(): self
    {
        $this->instance->unsetGatewaySyncErrorCode();
        return $this;
    }

    /**
     * Sets Gateway Sync Error Description field.
     *
     * @param string|null $value
     */
    public function gatewaySyncErrorDescription(?string $value): self
    {
        $this->instance->setGatewaySyncErrorDescription($value);
        return $this;
    }

    /**
     * Unsets Gateway Sync Error Description field.
     */
    public function unsetGatewaySyncErrorDescription(): self
    {
        $this->instance->unsetGatewaySyncErrorDescription();
        return $this;
    }

    /**
     * Sets Gateway Sync Status field.
     *
     * @param string|null $value
     */
    public function gatewaySyncStatus(?string $value): self
    {
        $this->instance->setGatewaySyncStatus($value);
        return $this;
    }

    /**
     * Unsets Gateway Sync Status field.
     */
    public function unsetGatewaySyncStatus(): self
    {
        $this->instance->unsetGatewaySyncStatus();
        return $this;
    }

    /**
     * Sets Main Reference field.
     *
     * @param int|null $value
     */
    public function mainReference(?int $value): self
    {
        $this->instance->setMainReference($value);
        return $this;
    }

    /**
     * Sets Order Card Reference field.
     *
     * @param int|null $value
     */
    public function orderCardReference(?int $value): self
    {
        $this->instance->setOrderCardReference($value);
        return $this;
    }

    /**
     * Sets Order Status field.
     *
     * @param string|null $value
     */
    public function orderStatus(?string $value): self
    {
        $this->instance->setOrderStatus($value);
        return $this;
    }

    /**
     * Unsets Order Status field.
     */
    public function unsetOrderStatus(): self
    {
        $this->instance->unsetOrderStatus();
        return $this;
    }

    /**
     * Sets Payer Id field.
     *
     * @param int|null $value
     */
    public function payerId(?int $value): self
    {
        $this->instance->setPayerId($value);
        return $this;
    }

    /**
     * Sets Payer Number field.
     *
     * @param string|null $value
     */
    public function payerNumber(?string $value): self
    {
        $this->instance->setPayerNumber($value);
        return $this;
    }

    /**
     * Unsets Payer Number field.
     */
    public function unsetPayerNumber(): self
    {
        $this->instance->unsetPayerNumber();
        return $this;
    }

    /**
     * Sets Processed Date field.
     *
     * @param string|null $value
     */
    public function processedDate(?string $value): self
    {
        $this->instance->setProcessedDate($value);
        return $this;
    }

    /**
     * Unsets Processed Date field.
     */
    public function unsetProcessedDate(): self
    {
        $this->instance->unsetProcessedDate();
        return $this;
    }

    /**
     * Sets Purchase Category Code field.
     *
     * @param string|null $value
     */
    public function purchaseCategoryCode(?string $value): self
    {
        $this->instance->setPurchaseCategoryCode($value);
        return $this;
    }

    /**
     * Unsets Purchase Category Code field.
     */
    public function unsetPurchaseCategoryCode(): self
    {
        $this->instance->unsetPurchaseCategoryCode();
        return $this;
    }

    /**
     * Sets Purchase Category Id field.
     *
     * @param int|null $value
     */
    public function purchaseCategoryId(?int $value): self
    {
        $this->instance->setPurchaseCategoryId($value);
        return $this;
    }

    /**
     * Unsets Purchase Category Id field.
     */
    public function unsetPurchaseCategoryId(): self
    {
        $this->instance->unsetPurchaseCategoryId();
        return $this;
    }

    /**
     * Sets Purchase Category Name field.
     *
     * @param string|null $value
     */
    public function purchaseCategoryName(?string $value): self
    {
        $this->instance->setPurchaseCategoryName($value);
        return $this;
    }

    /**
     * Unsets Purchase Category Name field.
     */
    public function unsetPurchaseCategoryName(): self
    {
        $this->instance->unsetPurchaseCategoryName();
        return $this;
    }

    /**
     * Sets Submitted Date field.
     *
     * @param string|null $value
     */
    public function submittedDate(?string $value): self
    {
        $this->instance->setSubmittedDate($value);
        return $this;
    }

    /**
     * Unsets Submitted Date field.
     */
    public function unsetSubmittedDate(): self
    {
        $this->instance->unsetSubmittedDate();
        return $this;
    }

    /**
     * Sets Sync Processed Date field.
     *
     * @param string|null $value
     */
    public function syncProcessedDate(?string $value): self
    {
        $this->instance->setSyncProcessedDate($value);
        return $this;
    }

    /**
     * Unsets Sync Processed Date field.
     */
    public function unsetSyncProcessedDate(): self
    {
        $this->instance->unsetSyncProcessedDate();
        return $this;
    }

    /**
     * Sets Sync Requested Date field.
     *
     * @param string|null $value
     */
    public function syncRequestedDate(?string $value): self
    {
        $this->instance->setSyncRequestedDate($value);
        return $this;
    }

    /**
     * Unsets Sync Requested Date field.
     */
    public function unsetSyncRequestedDate(): self
    {
        $this->instance->unsetSyncRequestedDate();
        return $this;
    }

    /**
     * Sets VRN field.
     *
     * @param string|null $value
     */
    public function vRN(?string $value): self
    {
        $this->instance->setVRN($value);
        return $this;
    }

    /**
     * Unsets VRN field.
     */
    public function unsetVRN(): self
    {
        $this->instance->unsetVRN();
        return $this;
    }

    /**
     * Sets Order Request Id field.
     *
     * @param string|null $value
     */
    public function orderRequestId(?string $value): self
    {
        $this->instance->setOrderRequestId($value);
        return $this;
    }

    /**
     * Unsets Order Request Id field.
     */
    public function unsetOrderRequestId(): self
    {
        $this->instance->unsetOrderRequestId();
        return $this;
    }

    /**
     * Sets Expiry Date field.
     *
     * @param string|null $value
     */
    public function expiryDate(?string $value): self
    {
        $this->instance->setExpiryDate($value);
        return $this;
    }

    /**
     * Unsets Expiry Date field.
     */
    public function unsetExpiryDate(): self
    {
        $this->instance->unsetExpiryDate();
        return $this;
    }

    /**
     * Sets Client Reference Id field.
     *
     * @param string|null $value
     */
    public function clientReferenceId(?string $value): self
    {
        $this->instance->setClientReferenceId($value);
        return $this;
    }

    /**
     * Unsets Client Reference Id field.
     */
    public function unsetClientReferenceId(): self
    {
        $this->instance->unsetClientReferenceId();
        return $this;
    }

    /**
     * Sets Status Description field.
     *
     * @param string|null $value
     */
    public function statusDescription(?string $value): self
    {
        $this->instance->setStatusDescription($value);
        return $this;
    }

    /**
     * Unsets Status Description field.
     */
    public function unsetStatusDescription(): self
    {
        $this->instance->unsetStatusDescription();
        return $this;
    }

    /**
     * Sets Col Co Id field.
     *
     * @param int|null $value
     */
    public function colCoId(?int $value): self
    {
        $this->instance->setColCoId($value);
        return $this;
    }

    /**
     * Unsets Col Co Id field.
     */
    public function unsetColCoId(): self
    {
        $this->instance->unsetColCoId();
        return $this;
    }

    /**
     * Initializes a new Order Card Enquiry object.
     */
    public function build(): OrderCardEnquiry
    {
        return CoreHelper::clone($this->instance);
    }
}
