<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellCardManagementAPIsLib\Models\PINReminderReference;

/**
 * Builder for model PINReminderReference
 *
 * @see PINReminderReference
 */
class PINReminderReferenceBuilder
{
    /**
     * @var PINReminderReference
     */
    private $instance;

    private function __construct(PINReminderReference $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new PIN Reminder Reference Builder object.
     */
    public static function init(): self
    {
        return new self(new PINReminderReference());
    }

    /**
     * Sets Card Id field.
     *
     * @param int|null $value
     */
    public function cardId(?int $value): self
    {
        $this->instance->setCardId($value);
        return $this;
    }

    /**
     * Unsets Card Id field.
     */
    public function unsetCardId(): self
    {
        $this->instance->unsetCardId();
        return $this;
    }

    /**
     * Sets PANID field.
     *
     * @param int|null $value
     */
    public function pANID(?int $value): self
    {
        $this->instance->setPANID($value);
        return $this;
    }

    /**
     * Unsets PANID field.
     */
    public function unsetPANID(): self
    {
        $this->instance->unsetPANID();
        return $this;
    }

    /**
     * Sets PAN field.
     *
     * @param int|null $value
     */
    public function pAN(?int $value): self
    {
        $this->instance->setPAN($value);
        return $this;
    }

    /**
     * Unsets PAN field.
     */
    public function unsetPAN(): self
    {
        $this->instance->unsetPAN();
        return $this;
    }

    /**
     * Sets Card Expiry Date field.
     *
     * @param string|null $value
     */
    public function cardExpiryDate(?string $value): self
    {
        $this->instance->setCardExpiryDate($value);
        return $this;
    }

    /**
     * Unsets Card Expiry Date field.
     */
    public function unsetCardExpiryDate(): self
    {
        $this->instance->unsetCardExpiryDate();
        return $this;
    }

    /**
     * Sets Reference Id field.
     *
     * @param int|null $value
     */
    public function referenceId(?int $value): self
    {
        $this->instance->setReferenceId($value);
        return $this;
    }

    /**
     * Initializes a new PIN Reminder Reference object.
     */
    public function build(): PINReminderReference
    {
        return CoreHelper::clone($this->instance);
    }
}
