<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellCardManagementAPIsLib\Models\PINReminderResponse;

/**
 * Builder for model PINReminderResponse
 *
 * @see PINReminderResponse
 */
class PINReminderResponseBuilder
{
    /**
     * @var PINReminderResponse
     */
    private $instance;

    private function __construct(PINReminderResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new pinreminder response Builder object.
     */
    public static function init(): self
    {
        return new self(new PINReminderResponse());
    }

    /**
     * Sets request id field.
     */
    public function requestId(?string $value): self
    {
        $this->instance->setRequestId($value);
        return $this;
    }

    /**
     * Sets main reference field.
     */
    public function mainReference(?int $value): self
    {
        $this->instance->setMainReference($value);
        return $this;
    }

    /**
     * Sets status field.
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Sets data field.
     */
    public function data(?array $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Initializes a new pinreminder response object.
     */
    public function build(): PINReminderResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
