<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellCardManagementAPIsLib\Models\ProductRestrictionCard;

/**
 * Builder for model ProductRestrictionCard
 *
 * @see ProductRestrictionCard
 */
class ProductRestrictionCardBuilder
{
    /**
     * @var ProductRestrictionCard
     */
    private $instance;

    private function __construct(ProductRestrictionCard $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new product restriction card Builder object.
     */
    public static function init(): self
    {
        return new self(new ProductRestrictionCard());
    }

    /**
     * Sets products field.
     */
    public function products(?array $value): self
    {
        $this->instance->setProducts($value);
        return $this;
    }

    /**
     * Sets product groups field.
     */
    public function productGroups(?array $value): self
    {
        $this->instance->setProductGroups($value);
        return $this;
    }

    /**
     * Initializes a new product restriction card object.
     */
    public function build(): ProductRestrictionCard
    {
        return CoreHelper::clone($this->instance);
    }
}
