<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellCardManagementAPIsLib\Models\PurchaseCategoryRequest;

/**
 * Builder for model PurchaseCategoryRequest
 *
 * @see PurchaseCategoryRequest
 */
class PurchaseCategoryRequestBuilder
{
    /**
     * @var PurchaseCategoryRequest
     */
    private $instance;

    private function __construct(PurchaseCategoryRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Purchase Category Request Builder object.
     */
    public static function init(): self
    {
        return new self(new PurchaseCategoryRequest());
    }

    /**
     * Sets Request Id field.
     *
     * @param string|null $value
     */
    public function requestId(?string $value): self
    {
        $this->instance->setRequestId($value);
        return $this;
    }

    /**
     * Sets Col Co Code field.
     *
     * @param int|null $value
     */
    public function colCoCode(?int $value): self
    {
        $this->instance->setColCoCode($value);
        return $this;
    }

    /**
     * Unsets Col Co Code field.
     */
    public function unsetColCoCode(): self
    {
        $this->instance->unsetColCoCode();
        return $this;
    }

    /**
     * Sets Col Co Id field.
     *
     * @param int|null $value
     */
    public function colCoId(?int $value): self
    {
        $this->instance->setColCoId($value);
        return $this;
    }

    /**
     * Unsets Col Co Id field.
     */
    public function unsetColCoId(): self
    {
        $this->instance->unsetColCoId();
        return $this;
    }

    /**
     * Sets Card Type Id field.
     *
     * @param int|null $value
     */
    public function cardTypeId(?int $value): self
    {
        $this->instance->setCardTypeId($value);
        return $this;
    }

    /**
     * Unsets Card Type Id field.
     */
    public function unsetCardTypeId(): self
    {
        $this->instance->unsetCardTypeId();
        return $this;
    }

    /**
     * Sets Purchase Category Id field.
     *
     * @param int|null $value
     */
    public function purchaseCategoryId(?int $value): self
    {
        $this->instance->setPurchaseCategoryId($value);
        return $this;
    }

    /**
     * Sets Language Code field.
     *
     * @param string|null $value
     */
    public function languageCode(?string $value): self
    {
        $this->instance->setLanguageCode($value);
        return $this;
    }

    /**
     * Initializes a new Purchase Category Request object.
     */
    public function build(): PurchaseCategoryRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
