<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellCardManagementAPIsLib\Models\ErrorStatus;
use ShellCardManagementAPIsLib\Models\PurchaseCategory1AllOf0;
use ShellCardManagementAPIsLib\Models\PurchaseCategoryResponse;

/**
 * Builder for model PurchaseCategoryResponse
 *
 * @see PurchaseCategoryResponse
 */
class PurchaseCategoryResponseBuilder
{
    /**
     * @var PurchaseCategoryResponse
     */
    private $instance;

    private function __construct(PurchaseCategoryResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Purchase Category Response Builder object.
     */
    public static function init(): self
    {
        return new self(new PurchaseCategoryResponse());
    }

    /**
     * Sets Purchase Categories field.
     *
     * @param PurchaseCategory1AllOf0[]|null $value
     */
    public function purchaseCategories(?array $value): self
    {
        $this->instance->setPurchaseCategories($value);
        return $this;
    }

    /**
     * Sets Error field.
     *
     * @param ErrorStatus|null $value
     */
    public function error(?ErrorStatus $value): self
    {
        $this->instance->setError($value);
        return $this;
    }

    /**
     * Initializes a new Purchase Category Response object.
     */
    public function build(): PurchaseCategoryResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
