<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellCardManagementAPIsLib\Models\DayTimeRestrictions;
use ShellCardManagementAPIsLib\Models\LocationRestriction;
use ShellCardManagementAPIsLib\Models\Restriction;
use ShellCardManagementAPIsLib\Models\SearchProductRestriction;
use ShellCardManagementAPIsLib\Models\UsageRestrictionsCard;

/**
 * Builder for model Restriction
 *
 * @see Restriction
 */
class RestrictionBuilder
{
    /**
     * @var Restriction
     */
    private $instance;

    private function __construct(Restriction $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Restriction Builder object.
     */
    public static function init(): self
    {
        return new self(new Restriction());
    }

    /**
     * Sets Usage Restrictions field.
     *
     * @param UsageRestrictionsCard|null $value
     */
    public function usageRestrictions(?UsageRestrictionsCard $value): self
    {
        $this->instance->setUsageRestrictions($value);
        return $this;
    }

    /**
     * Sets Day Time Restrictions field.
     *
     * @param DayTimeRestrictions|null $value
     */
    public function dayTimeRestrictions(?DayTimeRestrictions $value): self
    {
        $this->instance->setDayTimeRestrictions($value);
        return $this;
    }

    /**
     * Sets Product Restrictions field.
     *
     * @param SearchProductRestriction|null $value
     */
    public function productRestrictions(?SearchProductRestriction $value): self
    {
        $this->instance->setProductRestrictions($value);
        return $this;
    }

    /**
     * Sets Location Restrictions field.
     *
     * @param LocationRestriction|null $value
     */
    public function locationRestrictions(?LocationRestriction $value): self
    {
        $this->instance->setLocationRestrictions($value);
        return $this;
    }

    /**
     * Initializes a new Restriction object.
     */
    public function build(): Restriction
    {
        return CoreHelper::clone($this->instance);
    }
}
