<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellCardManagementAPIsLib\Models\Accounts;
use ShellCardManagementAPIsLib\Models\RestrictionSearchCardRequestFilters;

/**
 * Builder for model RestrictionSearchCardRequestFilters
 *
 * @see RestrictionSearchCardRequestFilters
 */
class RestrictionSearchCardRequestFiltersBuilder
{
    /**
     * @var RestrictionSearchCardRequestFilters
     */
    private $instance;

    private function __construct(RestrictionSearchCardRequestFilters $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new restriction search card request filters Builder object.
     */
    public static function init(): self
    {
        return new self(new RestrictionSearchCardRequestFilters());
    }

    /**
     * Sets col co code field.
     */
    public function colCoCode(?int $value): self
    {
        $this->instance->setColCoCode($value);
        return $this;
    }

    /**
     * Sets col co id field.
     */
    public function colCoId(?int $value): self
    {
        $this->instance->setColCoId($value);
        return $this;
    }

    /**
     * Sets payer number field.
     */
    public function payerNumber(?string $value): self
    {
        $this->instance->setPayerNumber($value);
        return $this;
    }

    /**
     * Sets payer id field.
     */
    public function payerId(?int $value): self
    {
        $this->instance->setPayerId($value);
        return $this;
    }

    /**
     * Sets accounts field.
     */
    public function accounts(?Accounts $value): self
    {
        $this->instance->setAccounts($value);
        return $this;
    }

    /**
     * Sets bundle id field.
     */
    public function bundleId(?string $value): self
    {
        $this->instance->setBundleId($value);
        return $this;
    }

    /**
     * Unsets bundle id field.
     */
    public function unsetBundleId(): self
    {
        $this->instance->unsetBundleId();
        return $this;
    }

    /**
     * Sets cards field.
     */
    public function cards(?array $value): self
    {
        $this->instance->setCards($value);
        return $this;
    }

    /**
     * Sets include location restrictions field.
     */
    public function includeLocationRestrictions(?bool $value): self
    {
        $this->instance->setIncludeLocationRestrictions($value);
        return $this;
    }

    /**
     * Sets include inherited limits field.
     */
    public function includeInheritedLimits(?bool $value): self
    {
        $this->instance->setIncludeInheritedLimits($value);
        return $this;
    }

    /**
     * Sets include bundle details field.
     */
    public function includeBundleDetails(?bool $value): self
    {
        $this->instance->setIncludeBundleDetails($value);
        return $this;
    }

    /**
     * Initializes a new restriction search card request filters object.
     */
    public function build(): RestrictionSearchCardRequestFilters
    {
        return CoreHelper::clone($this->instance);
    }
}
