<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellCardManagementAPIsLib\Models\RestrictioncardsRes;

/**
 * Builder for model RestrictioncardsRes
 *
 * @see RestrictioncardsRes
 */
class RestrictioncardsResBuilder
{
    /**
     * @var RestrictioncardsRes
     */
    private $instance;

    private function __construct(RestrictioncardsRes $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new restrictioncards res Builder object.
     */
    public static function init(): self
    {
        return new self(new RestrictioncardsRes());
    }

    /**
     * Sets account id field.
     */
    public function accountId(?int $value): self
    {
        $this->instance->setAccountId($value);
        return $this;
    }

    /**
     * Sets account number field.
     */
    public function accountNumber(?string $value): self
    {
        $this->instance->setAccountNumber($value);
        return $this;
    }

    /**
     * Sets card id field.
     */
    public function cardId(?string $value): self
    {
        $this->instance->setCardId($value);
        return $this;
    }

    /**
     * Sets pan field.
     */
    public function pAN(?string $value): self
    {
        $this->instance->setPAN($value);
        return $this;
    }

    /**
     * Sets usage restriction status field.
     */
    public function usageRestrictionStatus(?string $value): self
    {
        $this->instance->setUsageRestrictionStatus($value);
        return $this;
    }

    /**
     * Sets usage restriction description field.
     */
    public function usageRestrictionDescription(?string $value): self
    {
        $this->instance->setUsageRestrictionDescription($value);
        return $this;
    }

    /**
     * Sets day time restriction status field.
     */
    public function dayTimeRestrictionStatus(?string $value): self
    {
        $this->instance->setDayTimeRestrictionStatus($value);
        return $this;
    }

    /**
     * Sets day time restriction description field.
     */
    public function dayTimeRestrictionDescription(?string $value): self
    {
        $this->instance->setDayTimeRestrictionDescription($value);
        return $this;
    }

    /**
     * Sets product restriction status field.
     */
    public function productRestrictionStatus(?string $value): self
    {
        $this->instance->setProductRestrictionStatus($value);
        return $this;
    }

    /**
     * Sets product restriction description field.
     */
    public function productRestrictionDescription(?string $value): self
    {
        $this->instance->setProductRestrictionDescription($value);
        return $this;
    }

    /**
     * Sets location restriction status field.
     */
    public function locationRestrictionStatus(?string $value): self
    {
        $this->instance->setLocationRestrictionStatus($value);
        return $this;
    }

    /**
     * Sets location restriction status description field.
     */
    public function locationRestrictionStatusDescription(?string $value): self
    {
        $this->instance->setLocationRestrictionStatusDescription($value);
        return $this;
    }

    /**
     * Sets validation error code field.
     */
    public function validationErrorCode(?string $value): self
    {
        $this->instance->setValidationErrorCode($value);
        return $this;
    }

    /**
     * Sets validation error description field.
     */
    public function validationErrorDescription(?string $value): self
    {
        $this->instance->setValidationErrorDescription($value);
        return $this;
    }

    /**
     * Initializes a new restrictioncards res object.
     */
    public function build(): RestrictioncardsRes
    {
        return CoreHelper::clone($this->instance);
    }
}
