<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellCardManagementAPIsLib\Models\RestrictionSearchCardRequestFiltersCardsItems;

/**
 * Builder for model RestrictionSearchCardRequestFiltersCardsItems
 *
 * @see RestrictionSearchCardRequestFiltersCardsItems
 */
class RestrictionSearchCardRequestFiltersCardsItemsBuilder
{
    /**
     * @var RestrictionSearchCardRequestFiltersCardsItems
     */
    private $instance;

    private function __construct(RestrictionSearchCardRequestFiltersCardsItems $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new restriction search card request filters cards items Builder object.
     */
    public static function init(): self
    {
        return new self(new RestrictionSearchCardRequestFiltersCardsItems());
    }

    /**
     * Sets pan field.
     */
    public function pAN(?string $value): self
    {
        $this->instance->setPAN($value);
        return $this;
    }

    /**
     * Sets card id field.
     */
    public function cardId(?int $value): self
    {
        $this->instance->setCardId($value);
        return $this;
    }

    /**
     * Initializes a new restriction search card request filters cards items object.
     */
    public function build(): RestrictionSearchCardRequestFiltersCardsItems
    {
        return CoreHelper::clone($this->instance);
    }
}
