<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellCardManagementAPIsLib\Models\ErrorStatus;
use ShellCardManagementAPIsLib\Models\Restriction;
use ShellCardManagementAPIsLib\Models\SearchCardRestrictionRes;

/**
 * Builder for model SearchCardRestrictionRes
 *
 * @see SearchCardRestrictionRes
 */
class SearchCardRestrictionResBuilder
{
    /**
     * @var SearchCardRestrictionRes
     */
    private $instance;

    private function __construct(SearchCardRestrictionRes $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new search card restriction res Builder object.
     */
    public static function init(): self
    {
        return new self(new SearchCardRestrictionRes());
    }

    /**
     * Sets request id field.
     */
    public function requestId(?string $value): self
    {
        $this->instance->setRequestId($value);
        return $this;
    }

    /**
     * Unsets request id field.
     */
    public function unsetRequestId(): self
    {
        $this->instance->unsetRequestId();
        return $this;
    }

    /**
     * Sets cards field.
     */
    public function cards(?array $value): self
    {
        $this->instance->setCards($value);
        return $this;
    }

    /**
     * Sets restrictions field.
     */
    public function restrictions(?Restriction $value): self
    {
        $this->instance->setRestrictions($value);
        return $this;
    }

    /**
     * Sets error field.
     */
    public function error(?ErrorStatus $value): self
    {
        $this->instance->setError($value);
        return $this;
    }

    /**
     * Initializes a new search card restriction res object.
     */
    public function build(): SearchCardRestrictionRes
    {
        return CoreHelper::clone($this->instance);
    }
}
