<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellCardManagementAPIsLib\Models\SearchAccountLimitResponseData;

/**
 * Builder for model SearchAccountLimitResponseData
 *
 * @see SearchAccountLimitResponseData
 */
class SearchAccountLimitResponseDataBuilder
{
    /**
     * @var SearchAccountLimitResponseData
     */
    private $instance;

    private function __construct(SearchAccountLimitResponseData $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new search account limit response data Builder object.
     */
    public static function init(): self
    {
        return new self(new SearchAccountLimitResponseData());
    }

    /**
     * Sets account id field.
     */
    public function accountId(?int $value): self
    {
        $this->instance->setAccountId($value);
        return $this;
    }

    /**
     * Unsets account id field.
     */
    public function unsetAccountId(): self
    {
        $this->instance->unsetAccountId();
        return $this;
    }

    /**
     * Sets account number field.
     */
    public function accountNumber(?string $value): self
    {
        $this->instance->setAccountNumber($value);
        return $this;
    }

    /**
     * Unsets account number field.
     */
    public function unsetAccountNumber(): self
    {
        $this->instance->unsetAccountNumber();
        return $this;
    }

    /**
     * Sets reference product field.
     */
    public function referenceProduct(?string $value): self
    {
        $this->instance->setReferenceProduct($value);
        return $this;
    }

    /**
     * Unsets reference product field.
     */
    public function unsetReferenceProduct(): self
    {
        $this->instance->unsetReferenceProduct();
        return $this;
    }

    /**
     * Sets restriction condition field.
     */
    public function restrictionCondition(?string $value): self
    {
        $this->instance->setRestrictionCondition($value);
        return $this;
    }

    /**
     * Unsets restriction condition field.
     */
    public function unsetRestrictionCondition(): self
    {
        $this->instance->unsetRestrictionCondition();
        return $this;
    }

    /**
     * Sets velocity limits field.
     */
    public function velocityLimits(?array $value): self
    {
        $this->instance->setVelocityLimits($value);
        return $this;
    }

    /**
     * Initializes a new search account limit response data object.
     */
    public function build(): SearchAccountLimitResponseData
    {
        return CoreHelper::clone($this->instance);
    }
}
