<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellCardManagementAPIsLib\Models\SubmittedMoveCard;

/**
 * Builder for model SubmittedMoveCard
 *
 * @see SubmittedMoveCard
 */
class SubmittedMoveCardBuilder
{
    /**
     * @var SubmittedMoveCard
     */
    private $instance;

    private function __construct(SubmittedMoveCard $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Submitted Move Card Builder object.
     */
    public static function init(): self
    {
        return new self(new SubmittedMoveCard());
    }

    /**
     * Sets Account Id field.
     *
     * @param string|null $value
     */
    public function accountId(?string $value): self
    {
        $this->instance->setAccountId($value);
        return $this;
    }

    /**
     * Sets Account Number field.
     *
     * @param string|null $value
     */
    public function accountNumber(?string $value): self
    {
        $this->instance->setAccountNumber($value);
        return $this;
    }

    /**
     * Sets Card Id field.
     *
     * @param string|null $value
     */
    public function cardId(?string $value): self
    {
        $this->instance->setCardId($value);
        return $this;
    }

    /**
     * Sets PAN field.
     *
     * @param string|null $value
     */
    public function pAN(?string $value): self
    {
        $this->instance->setPAN($value);
        return $this;
    }

    /**
     * Sets Move Card Reference field.
     *
     * @param string|null $value
     */
    public function moveCardReference(?string $value): self
    {
        $this->instance->setMoveCardReference($value);
        return $this;
    }

    /**
     * Initializes a new Submitted Move Card object.
     */
    public function build(): SubmittedMoveCard
    {
        return CoreHelper::clone($this->instance);
    }
}
