<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellCardManagementAPIsLib\Models\SearchCard;
use ShellCardManagementAPIsLib\Models\SummaryRequest;

/**
 * Builder for model SummaryRequest
 *
 * @see SummaryRequest
 */
class SummaryRequestBuilder
{
    /**
     * @var SummaryRequest
     */
    private $instance;

    private function __construct(SummaryRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Summary Request Builder object.
     */
    public static function init(): self
    {
        return new self(new SummaryRequest());
    }

    /**
     * Sets Account Id field.
     *
     * @param int|null $value
     */
    public function accountId(?int $value): self
    {
        $this->instance->setAccountId($value);
        return $this;
    }

    /**
     * Unsets Account Id field.
     */
    public function unsetAccountId(): self
    {
        $this->instance->unsetAccountId();
        return $this;
    }

    /**
     * Sets Account Number field.
     *
     * @param string|null $value
     */
    public function accountNumber(?string $value): self
    {
        $this->instance->setAccountNumber($value);
        return $this;
    }

    /**
     * Unsets Account Number field.
     */
    public function unsetAccountNumber(): self
    {
        $this->instance->unsetAccountNumber();
        return $this;
    }

    /**
     * Sets Col Co Code field.
     *
     * @param int|null $value
     */
    public function colCoCode(?int $value): self
    {
        $this->instance->setColCoCode($value);
        return $this;
    }

    /**
     * Unsets Col Co Code field.
     */
    public function unsetColCoCode(): self
    {
        $this->instance->unsetColCoCode();
        return $this;
    }

    /**
     * Sets Col Co Country Code field.
     *
     * @param string|null $value
     */
    public function colCoCountryCode(?string $value): self
    {
        $this->instance->setColCoCountryCode($value);
        return $this;
    }

    /**
     * Unsets Col Co Country Code field.
     */
    public function unsetColCoCountryCode(): self
    {
        $this->instance->unsetColCoCountryCode();
        return $this;
    }

    /**
     * Sets Col Co Id field.
     *
     * @param int|null $value
     */
    public function colCoId(?int $value): self
    {
        $this->instance->setColCoId($value);
        return $this;
    }

    /**
     * Unsets Col Co Id field.
     */
    public function unsetColCoId(): self
    {
        $this->instance->unsetColCoId();
        return $this;
    }

    /**
     * Sets Payer Id field.
     *
     * @param int|null $value
     */
    public function payerId(?int $value): self
    {
        $this->instance->setPayerId($value);
        return $this;
    }

    /**
     * Unsets Payer Id field.
     */
    public function unsetPayerId(): self
    {
        $this->instance->unsetPayerId();
        return $this;
    }

    /**
     * Sets Payer Number field.
     *
     * @param string|null $value
     */
    public function payerNumber(?string $value): self
    {
        $this->instance->setPayerNumber($value);
        return $this;
    }

    /**
     * Unsets Payer Number field.
     */
    public function unsetPayerNumber(): self
    {
        $this->instance->unsetPayerNumber();
        return $this;
    }

    /**
     * Sets Card Group Id field.
     *
     * @param int|null $value
     */
    public function cardGroupId(?int $value): self
    {
        $this->instance->setCardGroupId($value);
        return $this;
    }

    /**
     * Unsets Card Group Id field.
     */
    public function unsetCardGroupId(): self
    {
        $this->instance->unsetCardGroupId();
        return $this;
    }

    /**
     * Sets Card Group Name field.
     *
     * @param string|null $value
     */
    public function cardGroupName(?string $value): self
    {
        $this->instance->setCardGroupName($value);
        return $this;
    }

    /**
     * Unsets Card Group Name field.
     */
    public function unsetCardGroupName(): self
    {
        $this->instance->unsetCardGroupName();
        return $this;
    }

    /**
     * Sets Card Status field.
     *
     * @param string[]|null $value
     */
    public function cardStatus(?array $value): self
    {
        $this->instance->setCardStatus($value);
        return $this;
    }

    /**
     * Sets Expiring In Days field.
     *
     * @param int|null $value
     */
    public function expiringInDays(?int $value): self
    {
        $this->instance->setExpiringInDays($value);
        return $this;
    }

    /**
     * Unsets Expiring In Days field.
     */
    public function unsetExpiringInDays(): self
    {
        $this->instance->unsetExpiringInDays();
        return $this;
    }

    /**
     * Sets Issued After field.
     *
     * @param string|null $value
     */
    public function issuedAfter(?string $value): self
    {
        $this->instance->setIssuedAfter($value);
        return $this;
    }

    /**
     * Unsets Issued After field.
     */
    public function unsetIssuedAfter(): self
    {
        $this->instance->unsetIssuedAfter();
        return $this;
    }

    /**
     * Sets PAN Ends With field.
     *
     * @param string|null $value
     */
    public function pANEndsWith(?string $value): self
    {
        $this->instance->setPANEndsWith($value);
        return $this;
    }

    /**
     * Unsets PAN Ends With field.
     */
    public function unsetPANEndsWith(): self
    {
        $this->instance->unsetPANEndsWith();
        return $this;
    }

    /**
     * Sets Driver Name field.
     *
     * @param string[]|null $value
     */
    public function driverName(?array $value): self
    {
        $this->instance->setDriverName($value);
        return $this;
    }

    /**
     * Sets Vehicle Registration Number field.
     *
     * @param string[]|null $value
     */
    public function vehicleRegistrationNumber(?array $value): self
    {
        $this->instance->setVehicleRegistrationNumber($value);
        return $this;
    }

    /**
     * Sets Include Cards field.
     *
     * @param SearchCard[]|null $value
     */
    public function includeCards(?array $value): self
    {
        $this->instance->setIncludeCards($value);
        return $this;
    }

    /**
     * Sets Exclude Cards field.
     *
     * @param SearchCard[]|null $value
     */
    public function excludeCards(?array $value): self
    {
        $this->instance->setExcludeCards($value);
        return $this;
    }

    /**
     * Sets Exclude Bundle Id field.
     *
     * @param string|null $value
     */
    public function excludeBundleId(?string $value): self
    {
        $this->instance->setExcludeBundleId($value);
        return $this;
    }

    /**
     * Unsets Exclude Bundle Id field.
     */
    public function unsetExcludeBundleId(): self
    {
        $this->instance->unsetExcludeBundleId();
        return $this;
    }

    /**
     * Sets Card Segment field.
     *
     * @param string|null $value
     */
    public function cardSegment(?string $value): self
    {
        $this->instance->setCardSegment($value);
        return $this;
    }

    /**
     * Unsets Card Segment field.
     */
    public function unsetCardSegment(): self
    {
        $this->instance->unsetCardSegment();
        return $this;
    }

    /**
     * Sets Purchase Category Code field.
     *
     * @param string|null $value
     */
    public function purchaseCategoryCode(?string $value): self
    {
        $this->instance->setPurchaseCategoryCode($value);
        return $this;
    }

    /**
     * Unsets Purchase Category Code field.
     */
    public function unsetPurchaseCategoryCode(): self
    {
        $this->instance->unsetPurchaseCategoryCode();
        return $this;
    }

    /**
     * Sets Card Type Code field.
     *
     * @param string|null $value
     */
    public function cardTypeCode(?string $value): self
    {
        $this->instance->setCardTypeCode($value);
        return $this;
    }

    /**
     * Unsets Card Type Code field.
     */
    public function unsetCardTypeCode(): self
    {
        $this->instance->unsetCardTypeCode();
        return $this;
    }

    /**
     * Sets Exclude Pending Renewal Cards field.
     *
     * @param bool|null $value
     */
    public function excludePendingRenewalCards(?bool $value): self
    {
        $this->instance->setExcludePendingRenewalCards($value);
        return $this;
    }

    /**
     * Sets Exclude Cancelled Cards field.
     *
     * @param bool|null $value
     */
    public function excludeCancelledCards(?bool $value): self
    {
        $this->instance->setExcludeCancelledCards($value);
        return $this;
    }

    /**
     * Sets Exclude Replaced Cards field.
     *
     * @param bool|null $value
     */
    public function excludeReplacedCards(?bool $value): self
    {
        $this->instance->setExcludeReplacedCards($value);
        return $this;
    }

    /**
     * Sets Exclude Fraud Cards field.
     *
     * @param bool|null $value
     */
    public function excludeFraudCards(?bool $value): self
    {
        $this->instance->setExcludeFraudCards($value);
        return $this;
    }

    /**
     * Sets Exclude Card Group Id field.
     *
     * @param int|null $value
     */
    public function excludeCardGroupId(?int $value): self
    {
        $this->instance->setExcludeCardGroupId($value);
        return $this;
    }

    /**
     * Unsets Exclude Card Group Id field.
     */
    public function unsetExcludeCardGroupId(): self
    {
        $this->instance->unsetExcludeCardGroupId();
        return $this;
    }

    /**
     * Sets Exclude Card Group Name field.
     *
     * @param string|null $value
     */
    public function excludeCardGroupName(?string $value): self
    {
        $this->instance->setExcludeCardGroupName($value);
        return $this;
    }

    /**
     * Unsets Exclude Card Group Name field.
     */
    public function unsetExcludeCardGroupName(): self
    {
        $this->instance->unsetExcludeCardGroupName();
        return $this;
    }

    /**
     * Sets Creation Date field.
     *
     * @param string|null $value
     */
    public function creationDate(?string $value): self
    {
        $this->instance->setCreationDate($value);
        return $this;
    }

    /**
     * Unsets Creation Date field.
     */
    public function unsetCreationDate(): self
    {
        $this->instance->unsetCreationDate();
        return $this;
    }

    /**
     * Sets Effective Date field.
     *
     * @param string|null $value
     */
    public function effectiveDate(?string $value): self
    {
        $this->instance->setEffectiveDate($value);
        return $this;
    }

    /**
     * Unsets Effective Date field.
     */
    public function unsetEffectiveDate(): self
    {
        $this->instance->unsetEffectiveDate();
        return $this;
    }

    /**
     * Sets Network field.
     *
     * @param string|null $value
     */
    public function network(?string $value): self
    {
        $this->instance->setNetwork($value);
        return $this;
    }

    /**
     * Unsets Network field.
     */
    public function unsetNetwork(): self
    {
        $this->instance->unsetNetwork();
        return $this;
    }

    /**
     * Sets Coverage field.
     *
     * @param string|null $value
     */
    public function coverage(?string $value): self
    {
        $this->instance->setCoverage($value);
        return $this;
    }

    /**
     * Unsets Coverage field.
     */
    public function unsetCoverage(): self
    {
        $this->instance->unsetCoverage();
        return $this;
    }

    /**
     * Sets Expiry Month field.
     *
     * @param string|null $value
     */
    public function expiryMonth(?string $value): self
    {
        $this->instance->setExpiryMonth($value);
        return $this;
    }

    /**
     * Unsets Expiry Month field.
     */
    public function unsetExpiryMonth(): self
    {
        $this->instance->unsetExpiryMonth();
        return $this;
    }

    /**
     * Sets Exclude Old Cards field.
     *
     * @param bool|null $value
     */
    public function excludeOldCards(?bool $value): self
    {
        $this->instance->setExcludeOldCards($value);
        return $this;
    }

    /**
     * Sets Reissue Setting field.
     *
     * @param string|null $value
     */
    public function reissueSetting(?string $value): self
    {
        $this->instance->setReissueSetting($value);
        return $this;
    }

    /**
     * Unsets Reissue Setting field.
     */
    public function unsetReissueSetting(): self
    {
        $this->instance->unsetReissueSetting();
        return $this;
    }

    /**
     * Sets Request Id field.
     *
     * @param string|null $value
     */
    public function requestId(?string $value): self
    {
        $this->instance->setRequestId($value);
        return $this;
    }

    /**
     * Initializes a new Summary Request object.
     */
    public function build(): SummaryRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
