<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellCardManagementAPIsLib\Models\SummaryOfBundleResponseDataItems;

/**
 * Builder for model SummaryOfBundleResponseDataItems
 *
 * @see SummaryOfBundleResponseDataItems
 */
class SummaryOfBundleResponseDataItemsBuilder
{
    /**
     * @var SummaryOfBundleResponseDataItems
     */
    private $instance;

    private function __construct(SummaryOfBundleResponseDataItems $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new summary of bundle response data items Builder object.
     */
    public static function init(): self
    {
        return new self(new SummaryOfBundleResponseDataItems());
    }

    /**
     * Sets payer id field.
     */
    public function payerId(?int $value): self
    {
        $this->instance->setPayerId($value);
        return $this;
    }

    /**
     * Unsets payer id field.
     */
    public function unsetPayerId(): self
    {
        $this->instance->unsetPayerId();
        return $this;
    }

    /**
     * Sets payer number field.
     */
    public function payerNumber(?string $value): self
    {
        $this->instance->setPayerNumber($value);
        return $this;
    }

    /**
     * Unsets payer number field.
     */
    public function unsetPayerNumber(): self
    {
        $this->instance->unsetPayerNumber();
        return $this;
    }

    /**
     * Sets account id field.
     */
    public function accountId(?int $value): self
    {
        $this->instance->setAccountId($value);
        return $this;
    }

    /**
     * Unsets account id field.
     */
    public function unsetAccountId(): self
    {
        $this->instance->unsetAccountId();
        return $this;
    }

    /**
     * Sets account number field.
     */
    public function accountNumber(?string $value): self
    {
        $this->instance->setAccountNumber($value);
        return $this;
    }

    /**
     * Unsets account number field.
     */
    public function unsetAccountNumber(): self
    {
        $this->instance->unsetAccountNumber();
        return $this;
    }

    /**
     * Sets count of cards not in bundle field.
     */
    public function countOfCardsNotInBundle(?int $value): self
    {
        $this->instance->setCountOfCardsNotInBundle($value);
        return $this;
    }

    /**
     * Unsets count of cards not in bundle field.
     */
    public function unsetCountOfCardsNotInBundle(): self
    {
        $this->instance->unsetCountOfCardsNotInBundle();
        return $this;
    }

    /**
     * Sets card bundles field.
     */
    public function cardBundles(?array $value): self
    {
        $this->instance->setCardBundles($value);
        return $this;
    }

    /**
     * Initializes a new summary of bundle response data items object.
     */
    public function build(): SummaryOfBundleResponseDataItems
    {
        return CoreHelper::clone($this->instance);
    }
}
