<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellCardManagementAPIsLib\Models\UpdateMPayRegStatusRequest;

/**
 * Builder for model UpdateMPayRegStatusRequest
 *
 * @see UpdateMPayRegStatusRequest
 */
class UpdateMPayRegStatusRequestBuilder
{
    /**
     * @var UpdateMPayRegStatusRequest
     */
    private $instance;

    private function __construct(UpdateMPayRegStatusRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new update mpay reg status request Builder object.
     */
    public static function init(): self
    {
        return new self(new UpdateMPayRegStatusRequest());
    }

    /**
     * Sets col co id field.
     */
    public function colCoId(?int $value): self
    {
        $this->instance->setColCoId($value);
        return $this;
    }

    /**
     * Sets col co code field.
     */
    public function colCoCode(?int $value): self
    {
        $this->instance->setColCoCode($value);
        return $this;
    }

    /**
     * Sets payer id field.
     */
    public function payerId(?int $value): self
    {
        $this->instance->setPayerId($value);
        return $this;
    }

    /**
     * Sets payer number field.
     */
    public function payerNumber(?string $value): self
    {
        $this->instance->setPayerNumber($value);
        return $this;
    }

    /**
     * Sets mpay requests field.
     */
    public function mPayRequests(?array $value): self
    {
        $this->instance->setMPayRequests($value);
        return $this;
    }

    /**
     * Initializes a new update mpay reg status request object.
     */
    public function build(): UpdateMPayRegStatusRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
