<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellCardManagementAPIsLib\Models\ErrorDetails;
use ShellCardManagementAPIsLib\Models\UpdateBundleResponse;

/**
 * Builder for model UpdateBundleResponse
 *
 * @see UpdateBundleResponse
 */
class UpdateBundleResponseBuilder
{
    /**
     * @var UpdateBundleResponse
     */
    private $instance;

    private function __construct(UpdateBundleResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new update bundle response Builder object.
     */
    public static function init(): self
    {
        return new self(new UpdateBundleResponse());
    }

    /**
     * Sets request id field.
     */
    public function requestId(?string $value): self
    {
        $this->instance->setRequestId($value);
        return $this;
    }

    /**
     * Sets status field.
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Sets errors field.
     */
    public function errors(?ErrorDetails $value): self
    {
        $this->instance->setErrors($value);
        return $this;
    }

    /**
     * Initializes a new update bundle response object.
     */
    public function build(): UpdateBundleResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
