<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellCardManagementAPIsLib\Models\UpdateCardGroupRequest;

/**
 * Builder for model UpdateCardGroupRequest
 *
 * @see UpdateCardGroupRequest
 */
class UpdateCardGroupRequestBuilder
{
    /**
     * @var UpdateCardGroupRequest
     */
    private $instance;

    private function __construct(UpdateCardGroupRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Update Card Group Request Builder object.
     */
    public static function init(): self
    {
        return new self(new UpdateCardGroupRequest());
    }

    /**
     * Sets Col Co Code field.
     *
     * @param int|null $value
     */
    public function colCoCode(?int $value): self
    {
        $this->instance->setColCoCode($value);
        return $this;
    }

    /**
     * Sets Col Co Id field.
     *
     * @param int|null $value
     */
    public function colCoId(?int $value): self
    {
        $this->instance->setColCoId($value);
        return $this;
    }

    /**
     * Sets Payer Number field.
     *
     * @param string|null $value
     */
    public function payerNumber(?string $value): self
    {
        $this->instance->setPayerNumber($value);
        return $this;
    }

    /**
     * Sets Payer Id field.
     *
     * @param int|null $value
     */
    public function payerId(?int $value): self
    {
        $this->instance->setPayerId($value);
        return $this;
    }

    /**
     * Sets Account Id field.
     *
     * @param int|null $value
     */
    public function accountId(?int $value): self
    {
        $this->instance->setAccountId($value);
        return $this;
    }

    /**
     * Sets Account Number field.
     *
     * @param string|null $value
     */
    public function accountNumber(?string $value): self
    {
        $this->instance->setAccountNumber($value);
        return $this;
    }

    /**
     * Sets Card Group Id field.
     *
     * @param int|null $value
     */
    public function cardGroupId(?int $value): self
    {
        $this->instance->setCardGroupId($value);
        return $this;
    }

    /**
     * Sets Card Group Name field.
     *
     * @param string|null $value
     */
    public function cardGroupName(?string $value): self
    {
        $this->instance->setCardGroupName($value);
        return $this;
    }

    /**
     * Sets Print On Card field.
     *
     * @param bool|null $value
     */
    public function printOnCard(?bool $value): self
    {
        $this->instance->setPrintOnCard($value);
        return $this;
    }

    /**
     * Sets Card Type Id field.
     *
     * @param int|null $value
     */
    public function cardTypeId(?int $value): self
    {
        $this->instance->setCardTypeId($value);
        return $this;
    }

    /**
     * Sets Terminate Card Group field.
     *
     * @param bool|null $value
     */
    public function terminateCardGroup(?bool $value): self
    {
        $this->instance->setTerminateCardGroup($value);
        return $this;
    }

    /**
     * Sets Move Cards field.
     *
     * @param bool|null $value
     */
    public function moveCards(?bool $value): self
    {
        $this->instance->setMoveCards($value);
        return $this;
    }

    /**
     * Sets Target Account Id field.
     *
     * @param int|null $value
     */
    public function targetAccountId(?int $value): self
    {
        $this->instance->setTargetAccountId($value);
        return $this;
    }

    /**
     * Sets Target Account Number field.
     *
     * @param string|null $value
     */
    public function targetAccountNumber(?string $value): self
    {
        $this->instance->setTargetAccountNumber($value);
        return $this;
    }

    /**
     * Sets Target New Card Group Name field.
     *
     * @param string|null $value
     */
    public function targetNewCardGroupName(?string $value): self
    {
        $this->instance->setTargetNewCardGroupName($value);
        return $this;
    }

    /**
     * Sets Target Card Group Id field.
     *
     * @param int|null $value
     */
    public function targetCardGroupId(?int $value): self
    {
        $this->instance->setTargetCardGroupId($value);
        return $this;
    }

    /**
     * Initializes a new Update Card Group Request object.
     */
    public function build(): UpdateCardGroupRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
