<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellCardManagementAPIsLib\Models\UpdateMPayRegStatusResponse;

/**
 * Builder for model UpdateMPayRegStatusResponse
 *
 * @see UpdateMPayRegStatusResponse
 */
class UpdateMPayRegStatusResponseBuilder
{
    /**
     * @var UpdateMPayRegStatusResponse
     */
    private $instance;

    private function __construct(UpdateMPayRegStatusResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Update M Pay Reg Status Response Builder object.
     */
    public static function init(): self
    {
        return new self(new UpdateMPayRegStatusResponse());
    }

    /**
     * Sets Request Id field.
     *
     * @param string|null $value
     */
    public function requestId(?string $value): self
    {
        $this->instance->setRequestId($value);
        return $this;
    }

    /**
     * Sets Status field.
     *
     * @param string|null $value
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Initializes a new Update M Pay Reg Status Response object.
     */
    public function build(): UpdateMPayRegStatusResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
