<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellCardManagementAPIsLib\Models\UpdateMPayRegStatusRequest;
use ShellCardManagementAPIsLib\Models\UpdateMPayRegStatusRequestMPayRequestsItems;

/**
 * Builder for model UpdateMPayRegStatusRequest
 *
 * @see UpdateMPayRegStatusRequest
 */
class UpdateMPayRegStatusRequestBuilder
{
    /**
     * @var UpdateMPayRegStatusRequest
     */
    private $instance;

    private function __construct(UpdateMPayRegStatusRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Update M Pay Reg Status Request Builder object.
     */
    public static function init(): self
    {
        return new self(new UpdateMPayRegStatusRequest());
    }

    /**
     * Sets Col Co Id field.
     *
     * @param int|null $value
     */
    public function colCoId(?int $value): self
    {
        $this->instance->setColCoId($value);
        return $this;
    }

    /**
     * Sets Col Co Code field.
     *
     * @param int|null $value
     */
    public function colCoCode(?int $value): self
    {
        $this->instance->setColCoCode($value);
        return $this;
    }

    /**
     * Sets Payer Id field.
     *
     * @param int|null $value
     */
    public function payerId(?int $value): self
    {
        $this->instance->setPayerId($value);
        return $this;
    }

    /**
     * Sets Payer Number field.
     *
     * @param string|null $value
     */
    public function payerNumber(?string $value): self
    {
        $this->instance->setPayerNumber($value);
        return $this;
    }

    /**
     * Sets M Pay Requests field.
     *
     * @param UpdateMPayRegStatusRequestMPayRequestsItems[]|null $value
     */
    public function mPayRequests(?array $value): self
    {
        $this->instance->setMPayRequests($value);
        return $this;
    }

    /**
     * Initializes a new Update M Pay Reg Status Request object.
     */
    public function build(): UpdateMPayRegStatusRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
