<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models\Builders;

use Core\Utils\CoreHelper;
use ShellCardManagementAPIsLib\Models\UsageRestriction;

/**
 * Builder for model UsageRestriction
 *
 * @see UsageRestriction
 */
class UsageRestrictionBuilder
{
    /**
     * @var UsageRestriction
     */
    private $instance;

    private function __construct(UsageRestriction $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Usage Restriction Builder object.
     */
    public static function init(): self
    {
        return new self(new UsageRestriction());
    }

    /**
     * Sets Level field.
     *
     * @param string|null $value
     */
    public function level(?string $value): self
    {
        $this->instance->setLevel($value);
        return $this;
    }

    /**
     * Sets Daily Spend field.
     *
     * @param float|null $value
     */
    public function dailySpend(?float $value): self
    {
        $this->instance->setDailySpend($value);
        return $this;
    }

    /**
     * Sets Daily Spend Accumulated field.
     *
     * @param float|null $value
     */
    public function dailySpendAccumulated(?float $value): self
    {
        $this->instance->setDailySpendAccumulated($value);
        return $this;
    }

    /**
     * Sets Daily Spend Balance field.
     *
     * @param float|null $value
     */
    public function dailySpendBalance(?float $value): self
    {
        $this->instance->setDailySpendBalance($value);
        return $this;
    }

    /**
     * Sets Daily Spend Override field.
     *
     * @param bool|null $value
     */
    public function dailySpendOverride(?bool $value): self
    {
        $this->instance->setDailySpendOverride($value);
        return $this;
    }

    /**
     * Sets Daily Spend Threshold field.
     *
     * @param float|null $value
     */
    public function dailySpendThreshold(?float $value): self
    {
        $this->instance->setDailySpendThreshold($value);
        return $this;
    }

    /**
     * Sets Weekly Spend field.
     *
     * @param float|null $value
     */
    public function weeklySpend(?float $value): self
    {
        $this->instance->setWeeklySpend($value);
        return $this;
    }

    /**
     * Sets Weekly Spend Accumulated field.
     *
     * @param float|null $value
     */
    public function weeklySpendAccumulated(?float $value): self
    {
        $this->instance->setWeeklySpendAccumulated($value);
        return $this;
    }

    /**
     * Sets Weekly Spend Balance field.
     *
     * @param float|null $value
     */
    public function weeklySpendBalance(?float $value): self
    {
        $this->instance->setWeeklySpendBalance($value);
        return $this;
    }

    /**
     * Sets Weekly Spend Override field.
     *
     * @param bool|null $value
     */
    public function weeklySpendOverride(?bool $value): self
    {
        $this->instance->setWeeklySpendOverride($value);
        return $this;
    }

    /**
     * Sets Weekly Spend Threshold field.
     *
     * @param float|null $value
     */
    public function weeklySpendThreshold(?float $value): self
    {
        $this->instance->setWeeklySpendThreshold($value);
        return $this;
    }

    /**
     * Sets Monthly Spend field.
     *
     * @param float|null $value
     */
    public function monthlySpend(?float $value): self
    {
        $this->instance->setMonthlySpend($value);
        return $this;
    }

    /**
     * Sets Monthly Spend Accumulated field.
     *
     * @param float|null $value
     */
    public function monthlySpendAccumulated(?float $value): self
    {
        $this->instance->setMonthlySpendAccumulated($value);
        return $this;
    }

    /**
     * Sets Monthly Spend Balance field.
     *
     * @param float|null $value
     */
    public function monthlySpendBalance(?float $value): self
    {
        $this->instance->setMonthlySpendBalance($value);
        return $this;
    }

    /**
     * Sets Monthly Spend Override field.
     *
     * @param bool|null $value
     */
    public function monthlySpendOverride(?bool $value): self
    {
        $this->instance->setMonthlySpendOverride($value);
        return $this;
    }

    /**
     * Sets Per Transaction Spend field.
     *
     * @param float|null $value
     */
    public function perTransactionSpend(?float $value): self
    {
        $this->instance->setPerTransactionSpend($value);
        return $this;
    }

    /**
     * Sets Per Transaction Spend Override field.
     *
     * @param bool|null $value
     */
    public function perTransactionSpendOverride(?bool $value): self
    {
        $this->instance->setPerTransactionSpendOverride($value);
        return $this;
    }

    /**
     * Sets Annual Spend field.
     *
     * @param float|null $value
     */
    public function annualSpend(?float $value): self
    {
        $this->instance->setAnnualSpend($value);
        return $this;
    }

    /**
     * Sets Annual Spend Accumulated field.
     *
     * @param float|null $value
     */
    public function annualSpendAccumulated(?float $value): self
    {
        $this->instance->setAnnualSpendAccumulated($value);
        return $this;
    }

    /**
     * Sets Annual Spend Balance field.
     *
     * @param float|null $value
     */
    public function annualSpendBalance(?float $value): self
    {
        $this->instance->setAnnualSpendBalance($value);
        return $this;
    }

    /**
     * Sets Annual Spend Override field.
     *
     * @param bool|null $value
     */
    public function annualSpendOverride(?bool $value): self
    {
        $this->instance->setAnnualSpendOverride($value);
        return $this;
    }

    /**
     * Sets Annual Spend Threshold field.
     *
     * @param float|null $value
     */
    public function annualSpendThreshold(?float $value): self
    {
        $this->instance->setAnnualSpendThreshold($value);
        return $this;
    }

    /**
     * Sets Life Time Spend field.
     *
     * @param float|null $value
     */
    public function lifeTimeSpend(?float $value): self
    {
        $this->instance->setLifeTimeSpend($value);
        return $this;
    }

    /**
     * Sets Life Time Spend Accumulated field.
     *
     * @param float|null $value
     */
    public function lifeTimeSpendAccumulated(?float $value): self
    {
        $this->instance->setLifeTimeSpendAccumulated($value);
        return $this;
    }

    /**
     * Sets Life Time Spend Balance field.
     *
     * @param float|null $value
     */
    public function lifeTimeSpendBalance(?float $value): self
    {
        $this->instance->setLifeTimeSpendBalance($value);
        return $this;
    }

    /**
     * Sets Life Time Spend Override field.
     *
     * @param bool|null $value
     */
    public function lifeTimeSpendOverride(?bool $value): self
    {
        $this->instance->setLifeTimeSpendOverride($value);
        return $this;
    }

    /**
     * Sets Life Time Spend Threshold field.
     *
     * @param float|null $value
     */
    public function lifeTimeSpendThreshold(?float $value): self
    {
        $this->instance->setLifeTimeSpendThreshold($value);
        return $this;
    }

    /**
     * Sets Daily Volume field.
     *
     * @param float|null $value
     */
    public function dailyVolume(?float $value): self
    {
        $this->instance->setDailyVolume($value);
        return $this;
    }

    /**
     * Sets Daily Volume Accumulated field.
     *
     * @param float|null $value
     */
    public function dailyVolumeAccumulated(?float $value): self
    {
        $this->instance->setDailyVolumeAccumulated($value);
        return $this;
    }

    /**
     * Sets Daily Volume Balance field.
     *
     * @param float|null $value
     */
    public function dailyVolumeBalance(?float $value): self
    {
        $this->instance->setDailyVolumeBalance($value);
        return $this;
    }

    /**
     * Sets Daily Volume Override field.
     *
     * @param float|null $value
     */
    public function dailyVolumeOverride(?float $value): self
    {
        $this->instance->setDailyVolumeOverride($value);
        return $this;
    }

    /**
     * Sets Daily Volume Threshold field.
     *
     * @param float|null $value
     */
    public function dailyVolumeThreshold(?float $value): self
    {
        $this->instance->setDailyVolumeThreshold($value);
        return $this;
    }

    /**
     * Sets Weekly Volume field.
     *
     * @param float|null $value
     */
    public function weeklyVolume(?float $value): self
    {
        $this->instance->setWeeklyVolume($value);
        return $this;
    }

    /**
     * Sets Weekly Volume Accumulated field.
     *
     * @param float|null $value
     */
    public function weeklyVolumeAccumulated(?float $value): self
    {
        $this->instance->setWeeklyVolumeAccumulated($value);
        return $this;
    }

    /**
     * Sets Weekly Volume Balance field.
     *
     * @param float|null $value
     */
    public function weeklyVolumeBalance(?float $value): self
    {
        $this->instance->setWeeklyVolumeBalance($value);
        return $this;
    }

    /**
     * Sets Weekly Volume Override field.
     *
     * @param bool|null $value
     */
    public function weeklyVolumeOverride(?bool $value): self
    {
        $this->instance->setWeeklyVolumeOverride($value);
        return $this;
    }

    /**
     * Sets Weekly Volume Threshold field.
     *
     * @param float|null $value
     */
    public function weeklyVolumeThreshold(?float $value): self
    {
        $this->instance->setWeeklyVolumeThreshold($value);
        return $this;
    }

    /**
     * Sets Monthly Volume field.
     *
     * @param float|null $value
     */
    public function monthlyVolume(?float $value): self
    {
        $this->instance->setMonthlyVolume($value);
        return $this;
    }

    /**
     * Sets Monthly Volume Accumulated field.
     *
     * @param float|null $value
     */
    public function monthlyVolumeAccumulated(?float $value): self
    {
        $this->instance->setMonthlyVolumeAccumulated($value);
        return $this;
    }

    /**
     * Sets Monthly Volume Balance field.
     *
     * @param float|null $value
     */
    public function monthlyVolumeBalance(?float $value): self
    {
        $this->instance->setMonthlyVolumeBalance($value);
        return $this;
    }

    /**
     * Sets Monthly Volume Override field.
     *
     * @param bool|null $value
     */
    public function monthlyVolumeOverride(?bool $value): self
    {
        $this->instance->setMonthlyVolumeOverride($value);
        return $this;
    }

    /**
     * Sets Monthly Volume Threshold field.
     *
     * @param float|null $value
     */
    public function monthlyVolumeThreshold(?float $value): self
    {
        $this->instance->setMonthlyVolumeThreshold($value);
        return $this;
    }

    /**
     * Sets Per Transaction Volume field.
     *
     * @param float|null $value
     */
    public function perTransactionVolume(?float $value): self
    {
        $this->instance->setPerTransactionVolume($value);
        return $this;
    }

    /**
     * Sets Per Transaction Volume Override field.
     *
     * @param bool|null $value
     */
    public function perTransactionVolumeOverride(?bool $value): self
    {
        $this->instance->setPerTransactionVolumeOverride($value);
        return $this;
    }

    /**
     * Sets Annual Volume field.
     *
     * @param float|null $value
     */
    public function annualVolume(?float $value): self
    {
        $this->instance->setAnnualVolume($value);
        return $this;
    }

    /**
     * Sets Annual Volume Accumulated field.
     *
     * @param float|null $value
     */
    public function annualVolumeAccumulated(?float $value): self
    {
        $this->instance->setAnnualVolumeAccumulated($value);
        return $this;
    }

    /**
     * Sets Annual Volume Balance field.
     *
     * @param float|null $value
     */
    public function annualVolumeBalance(?float $value): self
    {
        $this->instance->setAnnualVolumeBalance($value);
        return $this;
    }

    /**
     * Sets Annual Volume Override field.
     *
     * @param bool|null $value
     */
    public function annualVolumeOverride(?bool $value): self
    {
        $this->instance->setAnnualVolumeOverride($value);
        return $this;
    }

    /**
     * Sets Annual Volume Threshold field.
     *
     * @param float|null $value
     */
    public function annualVolumeThreshold(?float $value): self
    {
        $this->instance->setAnnualVolumeThreshold($value);
        return $this;
    }

    /**
     * Sets Life Time Volume field.
     *
     * @param float|null $value
     */
    public function lifeTimeVolume(?float $value): self
    {
        $this->instance->setLifeTimeVolume($value);
        return $this;
    }

    /**
     * Sets Life Time Volume Accumulated field.
     *
     * @param float|null $value
     */
    public function lifeTimeVolumeAccumulated(?float $value): self
    {
        $this->instance->setLifeTimeVolumeAccumulated($value);
        return $this;
    }

    /**
     * Sets Life Time Volume Balance field.
     *
     * @param float|null $value
     */
    public function lifeTimeVolumeBalance(?float $value): self
    {
        $this->instance->setLifeTimeVolumeBalance($value);
        return $this;
    }

    /**
     * Sets Life Time Volume Override field.
     *
     * @param bool|null $value
     */
    public function lifeTimeVolumeOverride(?bool $value): self
    {
        $this->instance->setLifeTimeVolumeOverride($value);
        return $this;
    }

    /**
     * Sets Life Time Volume Threshold field.
     *
     * @param float|null $value
     */
    public function lifeTimeVolumeThreshold(?float $value): self
    {
        $this->instance->setLifeTimeVolumeThreshold($value);
        return $this;
    }

    /**
     * Sets Daily Transaction Count field.
     *
     * @param float|null $value
     */
    public function dailyTransactionCount(?float $value): self
    {
        $this->instance->setDailyTransactionCount($value);
        return $this;
    }

    /**
     * Sets Daily Transaction Accumulated field.
     *
     * @param float|null $value
     */
    public function dailyTransactionAccumulated(?float $value): self
    {
        $this->instance->setDailyTransactionAccumulated($value);
        return $this;
    }

    /**
     * Sets Daily Transaction Balance field.
     *
     * @param float|null $value
     */
    public function dailyTransactionBalance(?float $value): self
    {
        $this->instance->setDailyTransactionBalance($value);
        return $this;
    }

    /**
     * Sets Daily Transaction Override field.
     *
     * @param bool|null $value
     */
    public function dailyTransactionOverride(?bool $value): self
    {
        $this->instance->setDailyTransactionOverride($value);
        return $this;
    }

    /**
     * Sets Daily Transaction Threshold field.
     *
     * @param float|null $value
     */
    public function dailyTransactionThreshold(?float $value): self
    {
        $this->instance->setDailyTransactionThreshold($value);
        return $this;
    }

    /**
     * Sets Weekly Transaction Count field.
     *
     * @param float|null $value
     */
    public function weeklyTransactionCount(?float $value): self
    {
        $this->instance->setWeeklyTransactionCount($value);
        return $this;
    }

    /**
     * Sets Weekly Transaction Accumulated field.
     *
     * @param float|null $value
     */
    public function weeklyTransactionAccumulated(?float $value): self
    {
        $this->instance->setWeeklyTransactionAccumulated($value);
        return $this;
    }

    /**
     * Sets Weekly Transaction Balance field.
     *
     * @param float|null $value
     */
    public function weeklyTransactionBalance(?float $value): self
    {
        $this->instance->setWeeklyTransactionBalance($value);
        return $this;
    }

    /**
     * Sets Weekly Transaction Override field.
     *
     * @param bool|null $value
     */
    public function weeklyTransactionOverride(?bool $value): self
    {
        $this->instance->setWeeklyTransactionOverride($value);
        return $this;
    }

    /**
     * Sets Weekly Transaction Threshold field.
     *
     * @param float|null $value
     */
    public function weeklyTransactionThreshold(?float $value): self
    {
        $this->instance->setWeeklyTransactionThreshold($value);
        return $this;
    }

    /**
     * Sets Monthly Transaction Count field.
     *
     * @param float|null $value
     */
    public function monthlyTransactionCount(?float $value): self
    {
        $this->instance->setMonthlyTransactionCount($value);
        return $this;
    }

    /**
     * Sets Monthly Transaction Accumulated field.
     *
     * @param float|null $value
     */
    public function monthlyTransactionAccumulated(?float $value): self
    {
        $this->instance->setMonthlyTransactionAccumulated($value);
        return $this;
    }

    /**
     * Sets Monthly Transaction Balance field.
     *
     * @param float|null $value
     */
    public function monthlyTransactionBalance(?float $value): self
    {
        $this->instance->setMonthlyTransactionBalance($value);
        return $this;
    }

    /**
     * Sets Monthly Transaction Override field.
     *
     * @param bool|null $value
     */
    public function monthlyTransactionOverride(?bool $value): self
    {
        $this->instance->setMonthlyTransactionOverride($value);
        return $this;
    }

    /**
     * Sets Monthly Transaction Threshold field.
     *
     * @param float|null $value
     */
    public function monthlyTransactionThreshold(?float $value): self
    {
        $this->instance->setMonthlyTransactionThreshold($value);
        return $this;
    }

    /**
     * Sets Annual Transaction Count field.
     *
     * @param float|null $value
     */
    public function annualTransactionCount(?float $value): self
    {
        $this->instance->setAnnualTransactionCount($value);
        return $this;
    }

    /**
     * Sets Annual Transaction Accumulated field.
     *
     * @param float|null $value
     */
    public function annualTransactionAccumulated(?float $value): self
    {
        $this->instance->setAnnualTransactionAccumulated($value);
        return $this;
    }

    /**
     * Sets Annual Transaction Balance field.
     *
     * @param float|null $value
     */
    public function annualTransactionBalance(?float $value): self
    {
        $this->instance->setAnnualTransactionBalance($value);
        return $this;
    }

    /**
     * Sets Annual Transaction Override field.
     *
     * @param bool|null $value
     */
    public function annualTransactionOverride(?bool $value): self
    {
        $this->instance->setAnnualTransactionOverride($value);
        return $this;
    }

    /**
     * Sets Annual Transaction Threshold field.
     *
     * @param float|null $value
     */
    public function annualTransactionThreshold(?float $value): self
    {
        $this->instance->setAnnualTransactionThreshold($value);
        return $this;
    }

    /**
     * Sets Life Time Transaction Count field.
     *
     * @param float|null $value
     */
    public function lifeTimeTransactionCount(?float $value): self
    {
        $this->instance->setLifeTimeTransactionCount($value);
        return $this;
    }

    /**
     * Sets Life Time Transaction Accumulated field.
     *
     * @param float|null $value
     */
    public function lifeTimeTransactionAccumulated(?float $value): self
    {
        $this->instance->setLifeTimeTransactionAccumulated($value);
        return $this;
    }

    /**
     * Sets Life Time Transaction Balance field.
     *
     * @param float|null $value
     */
    public function lifeTimeTransactionBalance(?float $value): self
    {
        $this->instance->setLifeTimeTransactionBalance($value);
        return $this;
    }

    /**
     * Sets Life Time Transaction Override field.
     *
     * @param bool|null $value
     */
    public function lifeTimeTransactionOverride(?bool $value): self
    {
        $this->instance->setLifeTimeTransactionOverride($value);
        return $this;
    }

    /**
     * Sets Life Time Transaction Threshold field.
     *
     * @param float|null $value
     */
    public function lifeTimeTransactionThreshold(?float $value): self
    {
        $this->instance->setLifeTimeTransactionThreshold($value);
        return $this;
    }

    /**
     * Initializes a new Usage Restriction object.
     */
    public function build(): UsageRestriction
    {
        return CoreHelper::clone($this->instance);
    }
}
