<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models;

use stdClass;

class AutoRenewCardResponseDataItems implements \JsonSerializable
{
    /**
     * @var array
     */
    private $autoRenewReferenceId = [];

    /**
     * @var array
     */
    private $cardIdAndPAN = [];

    /**
     * Returns Auto Renew Reference Id.
     * CardId and PAN of the card. ;( Semicolon is used as delimiter.
     */
    public function getAutoRenewReferenceId(): ?int
    {
        if (count($this->autoRenewReferenceId) == 0) {
            return null;
        }
        return $this->autoRenewReferenceId['value'];
    }

    /**
     * Sets Auto Renew Reference Id.
     * CardId and PAN of the card. ;( Semicolon is used as delimiter.
     *
     * @maps AutoRenewReferenceId
     */
    public function setAutoRenewReferenceId(?int $autoRenewReferenceId): void
    {
        $this->autoRenewReferenceId['value'] = $autoRenewReferenceId;
    }

    /**
     * Unsets Auto Renew Reference Id.
     * CardId and PAN of the card. ;( Semicolon is used as delimiter.
     */
    public function unsetAutoRenewReferenceId(): void
    {
        $this->autoRenewReferenceId = [];
    }

    /**
     * Returns Card Id and PAN.
     * Reference number for each individual auto renew card in the order.
     */
    public function getCardIdAndPAN(): ?string
    {
        if (count($this->cardIdAndPAN) == 0) {
            return null;
        }
        return $this->cardIdAndPAN['value'];
    }

    /**
     * Sets Card Id and PAN.
     * Reference number for each individual auto renew card in the order.
     *
     * @maps CardIdAndPAN
     */
    public function setCardIdAndPAN(?string $cardIdAndPAN): void
    {
        $this->cardIdAndPAN['value'] = $cardIdAndPAN;
    }

    /**
     * Unsets Card Id and PAN.
     * Reference number for each individual auto renew card in the order.
     */
    public function unsetCardIdAndPAN(): void
    {
        $this->cardIdAndPAN = [];
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (!empty($this->autoRenewReferenceId)) {
            $json['AutoRenewReferenceId'] = $this->autoRenewReferenceId['value'];
        }
        if (!empty($this->cardIdAndPAN)) {
            $json['CardIdAndPAN']         = $this->cardIdAndPAN['value'];
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
