<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models;

use stdClass;

class CardRestrictionResponse implements \JsonSerializable
{
    /**
     * @var array
     */
    private $requestId = [];

    /**
     * @var float|null
     */
    private $restrictionRequestReference;

    /**
     * @var RestrictioncardsRes[]|null
     */
    private $cards;

    /**
     * @var ErrorStatus|null
     */
    private $error;

    /**
     * Returns Request Id.
     * Request Id of the API call
     */
    public function getRequestId(): ?string
    {
        if (count($this->requestId) == 0) {
            return null;
        }
        return $this->requestId['value'];
    }

    /**
     * Sets Request Id.
     * Request Id of the API call
     *
     * @maps RequestId
     */
    public function setRequestId(?string $requestId): void
    {
        $this->requestId['value'] = $requestId;
    }

    /**
     * Unsets Request Id.
     * Request Id of the API call
     */
    public function unsetRequestId(): void
    {
        $this->requestId = [];
    }

    /**
     * Returns Restriction Request Reference.
     * Reference number for tracking the execution of the card restriction requests.
     */
    public function getRestrictionRequestReference(): ?float
    {
        return $this->restrictionRequestReference;
    }

    /**
     * Sets Restriction Request Reference.
     * Reference number for tracking the execution of the card restriction requests.
     *
     * @maps RestrictionRequestReference
     */
    public function setRestrictionRequestReference(?float $restrictionRequestReference): void
    {
        $this->restrictionRequestReference = $restrictionRequestReference;
    }

    /**
     * Returns Cards.
     *
     * @return RestrictioncardsRes[]|null
     */
    public function getCards(): ?array
    {
        return $this->cards;
    }

    /**
     * Sets Cards.
     *
     * @maps Cards
     *
     * @param RestrictioncardsRes[]|null $cards
     */
    public function setCards(?array $cards): void
    {
        $this->cards = $cards;
    }

    /**
     * Returns Error.
     */
    public function getError(): ?ErrorStatus
    {
        return $this->error;
    }

    /**
     * Sets Error.
     *
     * @maps Error
     */
    public function setError(?ErrorStatus $error): void
    {
        $this->error = $error;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (!empty($this->requestId)) {
            $json['RequestId']                   = $this->requestId['value'];
        }
        if (isset($this->restrictionRequestReference)) {
            $json['RestrictionRequestReference'] = $this->restrictionRequestReference;
        }
        if (isset($this->cards)) {
            $json['Cards']                       = $this->cards;
        }
        if (isset($this->error)) {
            $json['Error']                       = $this->error;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
