<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models;

use stdClass;

class CreateBundleRequest implements \JsonSerializable
{
    /**
     * @var array
     */
    private $colCoId = [];

    /**
     * @var array
     */
    private $colCoCode = [];

    /**
     * @var array
     */
    private $payerId = [];

    /**
     * @var string|null
     */
    private $payerNumber;

    /**
     * @var array
     */
    private $accountId = [];

    /**
     * @var array
     */
    private $accountNumber = [];

    /**
     * @var array
     */
    private $externalBundleId = [];

    /**
     * @var string|null
     */
    private $description;

    /**
     * @var string[]|null
     */
    private $cards;

    /**
     * @var array
     */
    private $restrictions = [];

    /**
     * Returns Col Co Id.
     * Collecting Company Id of the selected payer.
     *
     * Optional if ColCoCode is passed else Mandatory.
     *
     * Example:
     *
     * 1 for Philippines
     *
     * 5 for UK
     */
    public function getColCoId(): ?int
    {
        if (count($this->colCoId) == 0) {
            return null;
        }
        return $this->colCoId['value'];
    }

    /**
     * Sets Col Co Id.
     * Collecting Company Id of the selected payer.
     *
     * Optional if ColCoCode is passed else Mandatory.
     *
     * Example:
     *
     * 1 for Philippines
     *
     * 5 for UK
     *
     * @maps ColCoId
     */
    public function setColCoId(?int $colCoId): void
    {
        $this->colCoId['value'] = $colCoId;
    }

    /**
     * Unsets Col Co Id.
     * Collecting Company Id of the selected payer.
     *
     * Optional if ColCoCode is passed else Mandatory.
     *
     * Example:
     *
     * 1 for Philippines
     *
     * 5 for UK
     */
    public function unsetColCoId(): void
    {
        $this->colCoId = [];
    }

    /**
     * Returns Col Co Code.
     * Collecting Company Code (Shell Code) of the selected payer.
     *
     * Mandatory for serviced OUs such as Romania, Latvia, Lithuania, Estonia, Ukraine etc. It is optional
     * for other countries if ColCoID is provided.
     *
     * Example:
     *
     * 86 for Philippines
     *
     * 5 for UK
     */
    public function getColCoCode(): ?int
    {
        if (count($this->colCoCode) == 0) {
            return null;
        }
        return $this->colCoCode['value'];
    }

    /**
     * Sets Col Co Code.
     * Collecting Company Code (Shell Code) of the selected payer.
     *
     * Mandatory for serviced OUs such as Romania, Latvia, Lithuania, Estonia, Ukraine etc. It is optional
     * for other countries if ColCoID is provided.
     *
     * Example:
     *
     * 86 for Philippines
     *
     * 5 for UK
     *
     * @maps ColCoCode
     */
    public function setColCoCode(?int $colCoCode): void
    {
        $this->colCoCode['value'] = $colCoCode;
    }

    /**
     * Unsets Col Co Code.
     * Collecting Company Code (Shell Code) of the selected payer.
     *
     * Mandatory for serviced OUs such as Romania, Latvia, Lithuania, Estonia, Ukraine etc. It is optional
     * for other countries if ColCoID is provided.
     *
     * Example:
     *
     * 86 for Philippines
     *
     * 5 for UK
     */
    public function unsetColCoCode(): void
    {
        $this->colCoCode = [];
    }

    /**
     * Returns Payer Id.
     * Payer Id of the selected payer.
     *
     * Either PayerId or PayerNumber or both must be passed.
     *
     * Example: 123456
     */
    public function getPayerId(): ?int
    {
        if (count($this->payerId) == 0) {
            return null;
        }
        return $this->payerId['value'];
    }

    /**
     * Sets Payer Id.
     * Payer Id of the selected payer.
     *
     * Either PayerId or PayerNumber or both must be passed.
     *
     * Example: 123456
     *
     * @maps PayerId
     */
    public function setPayerId(?int $payerId): void
    {
        $this->payerId['value'] = $payerId;
    }

    /**
     * Unsets Payer Id.
     * Payer Id of the selected payer.
     *
     * Either PayerId or PayerNumber or both must be passed.
     *
     * Example: 123456
     */
    public function unsetPayerId(): void
    {
        $this->payerId = [];
    }

    /**
     * Returns Payer Number.
     * Payer Number of the selected payer.
     *
     * Either PayerId or PayerNumber or both must be passed.
     *
     * Example: GB000000123
     */
    public function getPayerNumber(): ?string
    {
        return $this->payerNumber;
    }

    /**
     * Sets Payer Number.
     * Payer Number of the selected payer.
     *
     * Either PayerId or PayerNumber or both must be passed.
     *
     * Example: GB000000123
     *
     * @maps PayerNumber
     */
    public function setPayerNumber(?string $payerNumber): void
    {
        $this->payerNumber = $payerNumber;
    }

    /**
     * Returns Account Id.
     * Account ID of the customer.
     *
     * Either AccountId or AccountNumber or both must be passed.
     *
     * Example: 123456
     */
    public function getAccountId(): ?int
    {
        if (count($this->accountId) == 0) {
            return null;
        }
        return $this->accountId['value'];
    }

    /**
     * Sets Account Id.
     * Account ID of the customer.
     *
     * Either AccountId or AccountNumber or both must be passed.
     *
     * Example: 123456
     *
     * @maps AccountId
     */
    public function setAccountId(?int $accountId): void
    {
        $this->accountId['value'] = $accountId;
    }

    /**
     * Unsets Account Id.
     * Account ID of the customer.
     *
     * Either AccountId or AccountNumber or both must be passed.
     *
     * Example: 123456
     */
    public function unsetAccountId(): void
    {
        $this->accountId = [];
    }

    /**
     * Returns Account Number.
     * Account Number of the customer.
     *
     * Either AccountId or AccountNumber or both must be passed.
     *
     * Example: GB000000123
     */
    public function getAccountNumber(): ?string
    {
        if (count($this->accountNumber) == 0) {
            return null;
        }
        return $this->accountNumber['value'];
    }

    /**
     * Sets Account Number.
     * Account Number of the customer.
     *
     * Either AccountId or AccountNumber or both must be passed.
     *
     * Example: GB000000123
     *
     * @maps AccountNumber
     */
    public function setAccountNumber(?string $accountNumber): void
    {
        $this->accountNumber['value'] = $accountNumber;
    }

    /**
     * Unsets Account Number.
     * Account Number of the customer.
     *
     * Either AccountId or AccountNumber or both must be passed.
     *
     * Example: GB000000123
     */
    public function unsetAccountNumber(): void
    {
        $this->accountNumber = [];
    }

    /**
     * Returns External Bundle Id.
     * Identifier of the bundle in external system.
     *
     * Optional.
     */
    public function getExternalBundleId(): ?string
    {
        if (count($this->externalBundleId) == 0) {
            return null;
        }
        return $this->externalBundleId['value'];
    }

    /**
     * Sets External Bundle Id.
     * Identifier of the bundle in external system.
     *
     * Optional.
     *
     * @maps ExternalBundleId
     */
    public function setExternalBundleId(?string $externalBundleId): void
    {
        $this->externalBundleId['value'] = $externalBundleId;
    }

    /**
     * Unsets External Bundle Id.
     * Identifier of the bundle in external system.
     *
     * Optional.
     */
    public function unsetExternalBundleId(): void
    {
        $this->externalBundleId = [];
    }

    /**
     * Returns Description.
     * A bundle description.
     *
     * Optional.
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     * A bundle description.
     *
     * Optional.
     *
     * @maps Description
     */
    public function setDescription(?string $description): void
    {
        $this->description = $description;
    }

    /**
     * Returns Cards.
     * List of Card PANs to be added in the bundle.
     *
     * Mandatory.
     *
     * Example: 7002051006629890645
     *
     * When PAN matches with multiple cards, the restriction will be applied on the latest issued card.
     *
     * @return string[]|null
     */
    public function getCards(): ?array
    {
        return $this->cards;
    }

    /**
     * Sets Cards.
     * List of Card PANs to be added in the bundle.
     *
     * Mandatory.
     *
     * Example: 7002051006629890645
     *
     * When PAN matches with multiple cards, the restriction will be applied on the latest issued card.
     *
     * @maps Cards
     *
     * @param string[]|null $cards
     */
    public function setCards(?array $cards): void
    {
        $this->cards = $cards;
    }

    /**
     * Returns Restrictions.
     */
    public function getRestrictions(): ?BundleRestriction
    {
        if (count($this->restrictions) == 0) {
            return null;
        }
        return $this->restrictions['value'];
    }

    /**
     * Sets Restrictions.
     *
     * @maps Restrictions
     */
    public function setRestrictions(?BundleRestriction $restrictions): void
    {
        $this->restrictions['value'] = $restrictions;
    }

    /**
     * Unsets Restrictions.
     */
    public function unsetRestrictions(): void
    {
        $this->restrictions = [];
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (!empty($this->colCoId)) {
            $json['ColCoId']          = $this->colCoId['value'];
        }
        if (!empty($this->colCoCode)) {
            $json['ColCoCode']        = $this->colCoCode['value'];
        }
        if (!empty($this->payerId)) {
            $json['PayerId']          = $this->payerId['value'];
        }
        if (isset($this->payerNumber)) {
            $json['PayerNumber']      = $this->payerNumber;
        }
        if (!empty($this->accountId)) {
            $json['AccountId']        = $this->accountId['value'];
        }
        if (!empty($this->accountNumber)) {
            $json['AccountNumber']    = $this->accountNumber['value'];
        }
        if (!empty($this->externalBundleId)) {
            $json['ExternalBundleId'] = $this->externalBundleId['value'];
        }
        if (isset($this->description)) {
            $json['Description']      = $this->description;
        }
        if (isset($this->cards)) {
            $json['Cards']            = $this->cards;
        }
        if (!empty($this->restrictions)) {
            $json['Restrictions']     = $this->restrictions['value'];
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
