<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models;

use stdClass;

class CreateCardGroupResponse implements \JsonSerializable
{
    /**
     * @var int|null
     */
    private $mainReference;

    /**
     * @var int|null
     */
    private $newCardGroupReference;

    /**
     * @var CreateCardGroupResponseSuccessfulRequestsItems[]|null
     */
    private $successfulRequests;

    /**
     * @var CreateCardGroupResponseErrorCardsItems[]|null
     */
    private $errorCards;

    /**
     * @var ErrorStatus|null
     */
    private $error;

    /**
     * @var string|null
     */
    private $requestId;

    /**
     * Returns Main Reference.
     * Reference number for tracking the execution of the requests – new Card Group creation and to move
     * the cards to the new card group.
     *
     * Reference number will be null when the validations of new card group parameters fail.
     */
    public function getMainReference(): ?int
    {
        return $this->mainReference;
    }

    /**
     * Sets Main Reference.
     * Reference number for tracking the execution of the requests – new Card Group creation and to move
     * the cards to the new card group.
     *
     * Reference number will be null when the validations of new card group parameters fail.
     *
     * @maps MainReference
     */
    public function setMainReference(?int $mainReference): void
    {
        $this->mainReference = $mainReference;
    }

    /**
     * Returns New Card Group Reference.
     * Reference number for tracking the execution of card group creation.
     *
     * Reference number will be null when the validations of new card group parameters fail.
     */
    public function getNewCardGroupReference(): ?int
    {
        return $this->newCardGroupReference;
    }

    /**
     * Sets New Card Group Reference.
     * Reference number for tracking the execution of card group creation.
     *
     * Reference number will be null when the validations of new card group parameters fail.
     *
     * @maps NewCardGroupReference
     */
    public function setNewCardGroupReference(?int $newCardGroupReference): void
    {
        $this->newCardGroupReference = $newCardGroupReference;
    }

    /**
     * Returns Successful Requests.
     * List of cards validated and submitted successfully for processing.
     *
     * @return CreateCardGroupResponseSuccessfulRequestsItems[]|null
     */
    public function getSuccessfulRequests(): ?array
    {
        return $this->successfulRequests;
    }

    /**
     * Sets Successful Requests.
     * List of cards validated and submitted successfully for processing.
     *
     * @maps SuccessfulRequests
     *
     * @param CreateCardGroupResponseSuccessfulRequestsItems[]|null $successfulRequests
     */
    public function setSuccessfulRequests(?array $successfulRequests): void
    {
        $this->successfulRequests = $successfulRequests;
    }

    /**
     * Returns Error Cards.
     * List of cards that failed validation and not submitted for processing.
     *
     * Entity: FailedCardReference
     *
     * This list will be empty when the validations of new card group parameters fail.
     *
     * @return CreateCardGroupResponseErrorCardsItems[]|null
     */
    public function getErrorCards(): ?array
    {
        return $this->errorCards;
    }

    /**
     * Sets Error Cards.
     * List of cards that failed validation and not submitted for processing.
     *
     * Entity: FailedCardReference
     *
     * This list will be empty when the validations of new card group parameters fail.
     *
     * @maps ErrorCards
     *
     * @param CreateCardGroupResponseErrorCardsItems[]|null $errorCards
     */
    public function setErrorCards(?array $errorCards): void
    {
        $this->errorCards = $errorCards;
    }

    /**
     * Returns Error.
     */
    public function getError(): ?ErrorStatus
    {
        return $this->error;
    }

    /**
     * Sets Error.
     *
     * @maps Error
     */
    public function setError(?ErrorStatus $error): void
    {
        $this->error = $error;
    }

    /**
     * Returns Request Id.
     * API Request Id
     */
    public function getRequestId(): ?string
    {
        return $this->requestId;
    }

    /**
     * Sets Request Id.
     * API Request Id
     *
     * @maps RequestId
     */
    public function setRequestId(?string $requestId): void
    {
        $this->requestId = $requestId;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->mainReference)) {
            $json['MainReference']         = $this->mainReference;
        }
        if (isset($this->newCardGroupReference)) {
            $json['NewCardGroupReference'] = $this->newCardGroupReference;
        }
        if (isset($this->successfulRequests)) {
            $json['SuccessfulRequests']    = $this->successfulRequests;
        }
        if (isset($this->errorCards)) {
            $json['ErrorCards']            = $this->errorCards;
        }
        if (isset($this->error)) {
            $json['Error']                 = $this->error;
        }
        if (isset($this->requestId)) {
            $json['RequestId']             = $this->requestId;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
