<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * Type of the reference number provided.<br />
 * Mandatory if ReferenceNumber is provided. Else optional.<br />
 * Allowed Values:<br />
 * 1=Main Reference(Main Order Reference Number returned in the output of Card/OrderCard service. <br
 * />
 * 2=Order Card Reference (Reference number for each individual card in the order submitted via
 * Card/OrderCard service. <br />
 * 3=Bulk Order Card Reference (Reference number returned in the response of bulkcardinterface
 * /UploadOrderCardTemplate. )
 */
class OrderCardEnquiryReqReferenceTypeEnum
{
    public const ENUM_1 = 1;

    public const ENUM_2 = 2;

    public const ENUM_3 = 3;

    private const _ALL_VALUES = [self::ENUM_1, self::ENUM_2, self::ENUM_3];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|int $value Value or a list/map of values to be checked
     *
     * @return array|null|int Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for OrderCardEnquiryReqReferenceTypeEnum.");
    }
}
