<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models;

use stdClass;

/**
 * This entity models the data that is received in the https request body of the PINReminder operation.
 */
class PINReminderRequest implements \JsonSerializable
{
    /**
     * @var int|null
     */
    private $accountId;

    /**
     * @var string|null
     */
    private $accountNumber;

    /**
     * @var int|null
     */
    private $colCoCode;

    /**
     * @var int|null
     */
    private $colCoId;

    /**
     * @var int|null
     */
    private $payerId;

    /**
     * @var string|null
     */
    private $payerNumber;

    /**
     * @var PINReminderCardDetails[]|null
     */
    private $pINReminderCardDetails;

    /**
     * Returns Account Id.
     * Account Id of the customer.<br />
     * Optional if AccountNumber is passed, else Mandatory.<br />
     * This input is a search criterion, if given.
     */
    public function getAccountId(): ?int
    {
        return $this->accountId;
    }

    /**
     * Sets Account Id.
     * Account Id of the customer.<br />
     * Optional if AccountNumber is passed, else Mandatory.<br />
     * This input is a search criterion, if given.
     *
     * @maps AccountId
     */
    public function setAccountId(?int $accountId): void
    {
        $this->accountId = $accountId;
    }

    /**
     * Returns Account Number.
     * Account Number of the customer.<br />
     * Optional if AccountId is passed, else Mandatory.<br />
     * This input is a search criterion, if given.
     */
    public function getAccountNumber(): ?string
    {
        return $this->accountNumber;
    }

    /**
     * Sets Account Number.
     * Account Number of the customer.<br />
     * Optional if AccountId is passed, else Mandatory.<br />
     * This input is a search criterion, if given.
     *
     * @maps AccountNumber
     */
    public function setAccountNumber(?string $accountNumber): void
    {
        $this->accountNumber = $accountNumber;
    }

    /**
     * Returns Col Co Code.
     * Collecting Company Code (Shell Code) of the selected payer. <br />
     * Mandatory for serviced OUs such as Romania, Latvia, Lithuania, Estonia, Ukraine etc. <br />
     * It is optional for other countries if ColCoID is provided.
     */
    public function getColCoCode(): ?int
    {
        return $this->colCoCode;
    }

    /**
     * Sets Col Co Code.
     * Collecting Company Code (Shell Code) of the selected payer. <br />
     * Mandatory for serviced OUs such as Romania, Latvia, Lithuania, Estonia, Ukraine etc. <br />
     * It is optional for other countries if ColCoID is provided.
     *
     * @maps ColCoCode
     */
    public function setColCoCode(?int $colCoCode): void
    {
        $this->colCoCode = $colCoCode;
    }

    /**
     * Returns Col Co Id.
     * Collecting Company Id of the selected payer<br />
     * Optional if ColCoCode is passed else Mandatory.
     */
    public function getColCoId(): ?int
    {
        return $this->colCoId;
    }

    /**
     * Sets Col Co Id.
     * Collecting Company Id of the selected payer<br />
     * Optional if ColCoCode is passed else Mandatory.
     *
     * @maps ColCoId
     */
    public function setColCoId(?int $colCoId): void
    {
        $this->colCoId = $colCoId;
    }

    /**
     * Returns Payer Id.
     * Payer Id (i.e. Customer Id of the Payment Customer of the selected payer.<br />
     * Optional if PayerNumber is passed else Mandatory
     */
    public function getPayerId(): ?int
    {
        return $this->payerId;
    }

    /**
     * Sets Payer Id.
     * Payer Id (i.e. Customer Id of the Payment Customer of the selected payer.<br />
     * Optional if PayerNumber is passed else Mandatory
     *
     * @maps PayerId
     */
    public function setPayerId(?int $payerId): void
    {
        $this->payerId = $payerId;
    }

    /**
     * Returns Payer Number.
     * Payer Number (Ex: GB000000123) of the selected payer.<br />
     * Optional if PayerId is passed else Mandatory
     */
    public function getPayerNumber(): ?string
    {
        return $this->payerNumber;
    }

    /**
     * Sets Payer Number.
     * Payer Number (Ex: GB000000123) of the selected payer.<br />
     * Optional if PayerId is passed else Mandatory
     *
     * @maps PayerNumber
     */
    public function setPayerNumber(?string $payerNumber): void
    {
        $this->payerNumber = $payerNumber;
    }

    /**
     * Returns P in Reminder Card Details.
     * List of PINReminderCardDetails entity. The fields of this entity are described below.
     *
     * @return PINReminderCardDetails[]|null
     */
    public function getPINReminderCardDetails(): ?array
    {
        return $this->pINReminderCardDetails;
    }

    /**
     * Sets P in Reminder Card Details.
     * List of PINReminderCardDetails entity. The fields of this entity are described below.
     *
     * @maps PINReminderCardDetails
     *
     * @param PINReminderCardDetails[]|null $pINReminderCardDetails
     */
    public function setPINReminderCardDetails(?array $pINReminderCardDetails): void
    {
        $this->pINReminderCardDetails = $pINReminderCardDetails;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->accountId)) {
            $json['AccountId']              = $this->accountId;
        }
        if (isset($this->accountNumber)) {
            $json['AccountNumber']          = $this->accountNumber;
        }
        if (isset($this->colCoCode)) {
            $json['ColCoCode']              = $this->colCoCode;
        }
        if (isset($this->colCoId)) {
            $json['ColCoId']                = $this->colCoId;
        }
        if (isset($this->payerId)) {
            $json['PayerId']                = $this->payerId;
        }
        if (isset($this->payerNumber)) {
            $json['PayerNumber']            = $this->payerNumber;
        }
        if (isset($this->pINReminderCardDetails)) {
            $json['PINReminderCardDetails'] = $this->pINReminderCardDetails;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
