<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models;

use ShellCardManagementAPIsLib\ApiHelper;
use stdClass;

class SearchCardRestrictionReq1 implements \JsonSerializable
{
    /**
     * @var SearchCardRestrictionReq|null
     */
    private $filters;

    /**
     * Returns Filters.
     */
    public function getFilters(): ?SearchCardRestrictionReq
    {
        return $this->filters;
    }

    /**
     * Sets Filters.
     *
     * @maps Filters
     */
    public function setFilters(?SearchCardRestrictionReq $filters): void
    {
        $this->filters = $filters;
    }

    /**
     * Converts the SearchCardRestrictionReq1 object to a human-readable string representation.
     *
     * @return string The string representation of the SearchCardRestrictionReq1 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('SearchCardRestrictionReq1', ['filters' => $this->filters]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->filters)) {
            $json['Filters'] = $this->filters;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
