<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib\Models;

use stdClass;

class UpdateBundleResponse implements \JsonSerializable
{
    /**
     * @var array
     */
    private $requestId = [];

    /**
     * @var ErrorStatus|null
     */
    private $requestActionStatus;

    /**
     * @var ErrorStatus|null
     */
    private $dayTimeRestrictionStatus;

    /**
     * @var ErrorStatus|null
     */
    private $locationRestrictionStatus;

    /**
     * @var ErrorStatus|null
     */
    private $productRestrictionStatus;

    /**
     * @var ErrorStatus|null
     */
    private $usageRestrictionStatus;

    /**
     * @var ErrorStatus|null
     */
    private $error;

    /**
     * Returns Request Id.
     * Request Id of the API call
     */
    public function getRequestId(): ?string
    {
        if (count($this->requestId) == 0) {
            return null;
        }
        return $this->requestId['value'];
    }

    /**
     * Sets Request Id.
     * Request Id of the API call
     *
     * @maps RequestId
     */
    public function setRequestId(?string $requestId): void
    {
        $this->requestId['value'] = $requestId;
    }

    /**
     * Unsets Request Id.
     * Request Id of the API call
     */
    public function unsetRequestId(): void
    {
        $this->requestId = [];
    }

    /**
     * Returns Request Action Status.
     */
    public function getRequestActionStatus(): ?ErrorStatus
    {
        return $this->requestActionStatus;
    }

    /**
     * Sets Request Action Status.
     *
     * @maps RequestActionStatus
     */
    public function setRequestActionStatus(?ErrorStatus $requestActionStatus): void
    {
        $this->requestActionStatus = $requestActionStatus;
    }

    /**
     * Returns Day Time Restriction Status.
     */
    public function getDayTimeRestrictionStatus(): ?ErrorStatus
    {
        return $this->dayTimeRestrictionStatus;
    }

    /**
     * Sets Day Time Restriction Status.
     *
     * @maps DayTimeRestrictionStatus
     */
    public function setDayTimeRestrictionStatus(?ErrorStatus $dayTimeRestrictionStatus): void
    {
        $this->dayTimeRestrictionStatus = $dayTimeRestrictionStatus;
    }

    /**
     * Returns Location Restriction Status.
     */
    public function getLocationRestrictionStatus(): ?ErrorStatus
    {
        return $this->locationRestrictionStatus;
    }

    /**
     * Sets Location Restriction Status.
     *
     * @maps LocationRestrictionStatus
     */
    public function setLocationRestrictionStatus(?ErrorStatus $locationRestrictionStatus): void
    {
        $this->locationRestrictionStatus = $locationRestrictionStatus;
    }

    /**
     * Returns Product Restriction Status.
     */
    public function getProductRestrictionStatus(): ?ErrorStatus
    {
        return $this->productRestrictionStatus;
    }

    /**
     * Sets Product Restriction Status.
     *
     * @maps ProductRestrictionStatus
     */
    public function setProductRestrictionStatus(?ErrorStatus $productRestrictionStatus): void
    {
        $this->productRestrictionStatus = $productRestrictionStatus;
    }

    /**
     * Returns Usage Restriction Status.
     */
    public function getUsageRestrictionStatus(): ?ErrorStatus
    {
        return $this->usageRestrictionStatus;
    }

    /**
     * Sets Usage Restriction Status.
     *
     * @maps UsageRestrictionStatus
     */
    public function setUsageRestrictionStatus(?ErrorStatus $usageRestrictionStatus): void
    {
        $this->usageRestrictionStatus = $usageRestrictionStatus;
    }

    /**
     * Returns Error.
     */
    public function getError(): ?ErrorStatus
    {
        return $this->error;
    }

    /**
     * Sets Error.
     *
     * @maps Error
     */
    public function setError(?ErrorStatus $error): void
    {
        $this->error = $error;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (!empty($this->requestId)) {
            $json['RequestId']                 = $this->requestId['value'];
        }
        if (isset($this->requestActionStatus)) {
            $json['RequestActionStatus']       = $this->requestActionStatus;
        }
        if (isset($this->dayTimeRestrictionStatus)) {
            $json['DayTimeRestrictionStatus']  = $this->dayTimeRestrictionStatus;
        }
        if (isset($this->locationRestrictionStatus)) {
            $json['LocationRestrictionStatus'] = $this->locationRestrictionStatus;
        }
        if (isset($this->productRestrictionStatus)) {
            $json['ProductRestrictionStatus']  = $this->productRestrictionStatus;
        }
        if (isset($this->usageRestrictionStatus)) {
            $json['UsageRestrictionStatus']    = $this->usageRestrictionStatus;
        }
        if (isset($this->error)) {
            $json['Error']                     = $this->error;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
