<?php

declare(strict_types=1);

/*
 * ShellCardManagementAPIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace ShellCardManagementAPIsLib;

/**
 * Baseurl aliases
 */
class Server
{
    public const DEFAULT_ = 'default';

    public const ACCESS_TOKEN_SERVER = 'access token server';
}
